In [1]:
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset
import matplotlib.pyplot as plt
import importlib
import dataset
from image_builder import *
from data_prepare import *
import data_fetch
from data_fetch import *
from data_fetch import _download_single, _read_mops_csv

importlib.reload(dataset)
importlib.reload(data_fetch)

In [2]:
from dataset import *
import os

START = "1993-01-01"
END = "2019-12-31"
TRAIN_END = "2000-12-31"
SAVE_DIR = "data"
Market = "US_1993_2020"
I = 5
R = 5
CRSP_DATA_DIR = resolve_crsp_data_dir()
print("CRSP data dir:", CRSP_DATA_DIR)

TICKERS, crsp_info = get_crsp_permno_universe(
    crsp_data_dir=CRSP_DATA_DIR,
    start=START,
    end=END,
    return_info=True,
)

print("permno 數量:", len(TICKERS))
display(crsp_info.head())

CRSP data dir: us_stock
permno 數量: 20721

  ticker permno  first_year  last_year  rows
0  10001  10001        1993       2017  5666
1  10002  10002        1993       2013  3873
2  10003  10003        1993       1995   665
3  10009  10009        1993       2000  1347
4  10010  10010        1993       1995   670

In [3]:

X_trainval, y_trainval, X_test, y_test, meta = build_research_dataset(
    tickers=TICKERS,
    start=START,
    end=END,
    I=I,
    R=R,
    train_end=TRAIN_END,
    save_dir=SAVE_DIR,
    Market=Market,
    price_source="crsp",
    crsp_data_dir=CRSP_DATA_DIR,
    checkpoint_every=1,
    resume=False,
    process_by="year",
    checkpoint_save_arrays=False,
    year_ticker_chunk_size=1000,
    max_workers=8,
)

Year-based CRSP build: pending years=[1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]

[I5/R5] build year: 1993

year 1993 chunks:   0%|                                                     | 0/21 [00:00<?, ?it/s]

year 1993 chunks:   5%|██▏                                          | 1/21 [00:22<07:31, 22.58s/it]

year 1993 chunks:  10%|████▎                                        | 2/21 [00:26<03:42, 11.72s/it]

year 1993 chunks:  14%|██████▍                                      | 3/21 [00:28<02:07,  7.07s/it]

year 1993 chunks:  19%|████████▌                                    | 4/21 [00:30<01:25,  5.03s/it]

year 1993 chunks:  24%|██████████▋                                  | 5/21 [00:39<01:46,  6.66s/it]

year 1993 chunks:  29%|████████████▊                                | 6/21 [01:04<03:10, 12.68s/it]

year 1993 chunks:  33%|███████████████                              | 7/21 [01:29<03:57, 16.99s/it]

year 1993 chunks:  38%|█████████████████▏                           | 8/21 [01:55<04:18, 19.86s/it]

year 1993 chunks:  43%|███████████████████▎                         | 9/21 [02:21<04:18, 21.52s/it]

year 1993 chunks:  48%|████████████████████▉                       | 10/21 [02:46<04:10, 22.76s/it]

year 1993 chunks:  52%|███████████████████████                     | 11/21 [03:02<03:25, 20.57s/it]

year 1993 chunks:  57%|█████████████████████████▏                  | 12/21 [03:07<02:21, 15.77s/it]

year 1993 chunks:  62%|███████████████████████████▏                | 13/21 [03:07<01:30, 11.29s/it]

year 1993 chunks:  67%|█████████████████████████████▎              | 14/21 [03:08<00:56,  8.08s/it]

year 1993 chunks:  71%|███████████████████████████████▍            | 15/21 [03:09<00:35,  5.86s/it]

year 1993 chunks:  76%|█████████████████████████████████▌          | 16/21 [03:10<00:22,  4.51s/it]

year 1993 chunks:  81%|███████████████████████████████████▌        | 17/21 [03:12<00:14,  3.64s/it]

year 1993 chunks:  86%|█████████████████████████████████████▋      | 18/21 [03:13<00:08,  2.86s/it]

year 1993 chunks:  90%|███████████████████████████████████████▊    | 19/21 [03:14<00:04,  2.36s/it]

year 1993 chunks:  95%|█████████████████████████████████████████▉  | 20/21 [03:15<00:02,  2.03s/it]

year 1993 chunks: 100%|████████████████████████████████████████████| 21/21 [03:16<00:00,  1.67s/it]

year 1993 chunks: 100%|████████████████████████████████████████████| 21/21 [03:16<00:00,  9.37s/it]

  done year 1993: 333280 images
  Checkpoint saved: 1 tickers done, 333280 images

[I5/R5] build year: 1994

year 1994 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 1994 chunks:   5%|███▏                                                                | 1/21 [00:26<08:52, 26.62s/it]

year 1994 chunks:  10%|██████▍                                                             | 2/21 [00:31<04:19, 13.67s/it]

year 1994 chunks:  14%|█████████▋                                                          | 3/21 [00:33<02:29,  8.28s/it]

year 1994 chunks:  19%|████████████▉                                                       | 4/21 [00:35<01:41,  5.96s/it]

year 1994 chunks:  24%|████████████████▏                                                   | 5/21 [00:47<02:07,  7.99s/it]

year 1994 chunks:  29%|███████████████████▍                                                | 6/21 [01:17<03:53, 15.55s/it]

year 1994 chunks:  33%|██████████████████████▋                                             | 7/21 [01:49<04:52, 20.91s/it]

year 1994 chunks:  38%|█████████████████████████▉                                          | 8/21 [02:21<05:17, 24.41s/it]

year 1994 chunks:  43%|█████████████████████████████▏                                      | 9/21 [02:53<05:20, 26.74s/it]

year 1994 chunks:  48%|███████████████████████████████▉                                   | 10/21 [03:24<05:11, 28.32s/it]

year 1994 chunks:  52%|███████████████████████████████████                                | 11/21 [03:57<04:55, 29.54s/it]

year 1994 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [04:18<04:03, 27.05s/it]

year 1994 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [04:23<02:43, 20.49s/it]

year 1994 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [04:24<01:42, 14.60s/it]

year 1994 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [04:25<01:03, 10.51s/it]

year 1994 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [04:27<00:39,  7.92s/it]

year 1994 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [04:29<00:24,  6.14s/it]

year 1994 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [04:31<00:14,  4.73s/it]

year 1994 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [04:33<00:07,  3.82s/it]

year 1994 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [04:34<00:03,  3.20s/it]

year 1994 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:37<00:00,  3.00s/it]

year 1994 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:37<00:00, 13.21s/it]

  done year 1994: 368862 images
  Checkpoint saved: 2 tickers done, 702142 images

[I5/R5] build year: 1995

year 1995 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 1995 chunks:   5%|███▏                                                                | 1/21 [00:26<08:46, 26.31s/it]

year 1995 chunks:  10%|██████▍                                                             | 2/21 [00:31<04:19, 13.64s/it]

year 1995 chunks:  14%|█████████▋                                                          | 3/21 [00:33<02:30,  8.35s/it]

year 1995 chunks:  19%|████████████▉                                                       | 4/21 [00:35<01:43,  6.11s/it]

year 1995 chunks:  24%|████████████████▏                                                   | 5/21 [00:47<02:12,  8.27s/it]

year 1995 chunks:  29%|███████████████████▍                                                | 6/21 [01:19<04:05, 16.34s/it]

year 1995 chunks:  33%|██████████████████████▋                                             | 7/21 [01:50<04:55, 21.12s/it]

year 1995 chunks:  38%|█████████████████████████▉                                          | 8/21 [02:23<05:22, 24.82s/it]

year 1995 chunks:  43%|█████████████████████████████▏                                      | 9/21 [02:52<05:11, 25.99s/it]

year 1995 chunks:  48%|███████████████████████████████▉                                   | 10/21 [03:23<05:04, 27.67s/it]

year 1995 chunks:  52%|███████████████████████████████████                                | 11/21 [03:55<04:48, 28.84s/it]

year 1995 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [04:26<04:25, 29.47s/it]

year 1995 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [04:46<03:33, 26.65s/it]

year 1995 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [04:51<02:22, 20.33s/it]

year 1995 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [04:53<01:28, 14.68s/it]

year 1995 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [04:55<00:54, 10.82s/it]

year 1995 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [04:57<00:32,  8.16s/it]

year 1995 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [04:58<00:18,  6.14s/it]

year 1995 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [05:00<00:09,  4.78s/it]

year 1995 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [05:02<00:03,  3.87s/it]

year 1995 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:03<00:00,  3.08s/it]

year 1995 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:03<00:00, 14.44s/it]

  done year 1995: 385371 images
  Checkpoint saved: 3 tickers done, 1087513 images

[I5/R5] build year: 1996

year 1996 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 1996 chunks:   5%|███▏                                                                | 1/21 [00:24<08:08, 24.41s/it]

year 1996 chunks:  10%|██████▍                                                             | 2/21 [00:28<04:01, 12.71s/it]

year 1996 chunks:  14%|█████████▋                                                          | 3/21 [00:30<02:20,  7.83s/it]

year 1996 chunks:  19%|████████████▉                                                       | 4/21 [00:33<01:38,  5.80s/it]

year 1996 chunks:  24%|████████████████▏                                                   | 5/21 [00:45<02:06,  7.93s/it]

year 1996 chunks:  29%|███████████████████▍                                                | 6/21 [01:16<03:59, 15.98s/it]

year 1996 chunks:  33%|██████████████████████▋                                             | 7/21 [01:46<04:44, 20.29s/it]

year 1996 chunks:  38%|█████████████████████████▉                                          | 8/21 [02:15<05:00, 23.10s/it]

year 1996 chunks:  43%|█████████████████████████████▏                                      | 9/21 [02:43<04:57, 24.79s/it]

year 1996 chunks:  48%|███████████████████████████████▉                                   | 10/21 [03:11<04:42, 25.67s/it]

year 1996 chunks:  52%|███████████████████████████████████                                | 11/21 [03:40<04:27, 26.78s/it]

year 1996 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [04:13<04:18, 28.73s/it]

year 1996 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [04:44<03:55, 29.43s/it]

year 1996 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [05:05<03:06, 26.68s/it]

year 1996 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [05:11<02:03, 20.58s/it]

year 1996 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [05:13<01:15, 15.04s/it]

year 1996 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [05:15<00:44, 11.06s/it]

year 1996 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [05:17<00:24,  8.18s/it]

year 1996 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [05:18<00:12,  6.21s/it]

year 1996 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [05:20<00:04,  4.83s/it]

year 1996 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:21<00:00,  3.72s/it]

year 1996 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:21<00:00, 15.31s/it]

  done year 1996: 410908 images
  Checkpoint saved: 4 tickers done, 1498421 images

[I5/R5] build year: 1997

year 1997 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 1997 chunks:   5%|███▏                                                                | 1/21 [00:22<07:28, 22.42s/it]

year 1997 chunks:  10%|██████▍                                                             | 2/21 [00:26<03:43, 11.75s/it]

year 1997 chunks:  14%|█████████▋                                                          | 3/21 [00:28<02:10,  7.27s/it]

year 1997 chunks:  19%|████████████▉                                                       | 4/21 [00:31<01:32,  5.44s/it]

year 1997 chunks:  24%|████████████████▏                                                   | 5/21 [00:45<02:15,  8.47s/it]

year 1997 chunks:  29%|███████████████████▍                                                | 6/21 [01:12<03:45, 15.01s/it]

year 1997 chunks:  33%|██████████████████████▋                                             | 7/21 [01:40<04:27, 19.09s/it]

year 1997 chunks:  38%|█████████████████████████▉                                          | 8/21 [02:07<04:40, 21.59s/it]

year 1997 chunks:  43%|█████████████████████████████▏                                      | 9/21 [02:31<04:28, 22.34s/it]

year 1997 chunks:  48%|███████████████████████████████▉                                   | 10/21 [02:59<04:27, 24.29s/it]

year 1997 chunks:  52%|███████████████████████████████████                                | 11/21 [03:26<04:11, 25.15s/it]

year 1997 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [03:55<03:54, 26.09s/it]

year 1997 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [04:26<03:40, 27.58s/it]

year 1997 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [05:01<03:29, 29.89s/it]

year 1997 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [05:23<02:44, 27.47s/it]

year 1997 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [05:29<01:44, 20.98s/it]

year 1997 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [05:31<01:00, 15.23s/it]

year 1997 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [05:32<00:33, 11.10s/it]

year 1997 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [05:34<00:16,  8.22s/it]

year 1997 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [05:35<00:06,  6.21s/it]

year 1997 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:36<00:00,  4.70s/it]

year 1997 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:36<00:00, 16.04s/it]

  done year 1997: 431698 images
  Checkpoint saved: 5 tickers done, 1930119 images

[I5/R5] build year: 1998

year 1998 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 1998 chunks:   5%|███▏                                                                | 1/21 [00:20<06:44, 20.24s/it]

year 1998 chunks:  10%|██████▍                                                             | 2/21 [00:24<03:24, 10.75s/it]

year 1998 chunks:  14%|█████████▋                                                          | 3/21 [00:26<02:00,  6.72s/it]

year 1998 chunks:  19%|████████████▉                                                       | 4/21 [00:28<01:26,  5.09s/it]

year 1998 chunks:  24%|████████████████▏                                                   | 5/21 [00:39<01:54,  7.13s/it]

year 1998 chunks:  29%|███████████████████▍                                                | 6/21 [01:05<03:22, 13.48s/it]

year 1998 chunks:  33%|██████████████████████▋                                             | 7/21 [01:31<04:05, 17.55s/it]

year 1998 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:59<04:31, 20.90s/it]

year 1998 chunks:  43%|█████████████████████████████▏                                      | 9/21 [02:21<04:15, 21.30s/it]

year 1998 chunks:  48%|███████████████████████████████▉                                   | 10/21 [02:44<04:00, 21.90s/it]

year 1998 chunks:  52%|███████████████████████████████████                                | 11/21 [03:09<03:47, 22.78s/it]

year 1998 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [03:34<03:31, 23.55s/it]

year 1998 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [04:02<03:19, 24.88s/it]

year 1998 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [04:37<03:15, 27.94s/it]

year 1998 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [05:09<02:54, 29.14s/it]

year 1998 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [05:29<02:11, 26.30s/it]

year 1998 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [05:33<01:18, 19.69s/it]

year 1998 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [05:35<00:42, 14.21s/it]

year 1998 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [05:36<00:20, 10.39s/it]

year 1998 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [05:38<00:07,  7.65s/it]

year 1998 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:39<00:00,  5.68s/it]

year 1998 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:39<00:00, 16.15s/it]

  done year 1998: 438264 images
  Checkpoint saved: 6 tickers done, 2368383 images

[I5/R5] build year: 1999

year 1999 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 1999 chunks:   5%|███▏                                                                | 1/21 [00:17<05:55, 17.77s/it]

year 1999 chunks:  10%|██████▍                                                             | 2/21 [00:21<03:00,  9.48s/it]

year 1999 chunks:  14%|█████████▋                                                          | 3/21 [00:23<01:48,  6.02s/it]

year 1999 chunks:  19%|████████████▉                                                       | 4/21 [00:25<01:17,  4.57s/it]

year 1999 chunks:  24%|████████████████▏                                                   | 5/21 [00:35<01:43,  6.49s/it]

year 1999 chunks:  29%|███████████████████▍                                                | 6/21 [00:59<03:04, 12.31s/it]

year 1999 chunks:  33%|██████████████████████▋                                             | 7/21 [01:22<03:42, 15.92s/it]

year 1999 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:44<03:51, 17.83s/it]

year 1999 chunks:  43%|█████████████████████████████▏                                      | 9/21 [02:07<03:53, 19.48s/it]

year 1999 chunks:  48%|███████████████████████████████▉                                   | 10/21 [02:28<03:37, 19.78s/it]

year 1999 chunks:  52%|███████████████████████████████████                                | 11/21 [02:49<03:23, 20.30s/it]

year 1999 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [03:10<03:04, 20.47s/it]

year 1999 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [03:33<02:50, 21.34s/it]

year 1999 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [03:59<02:38, 22.65s/it]

year 1999 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [04:28<02:28, 24.68s/it]

year 1999 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [04:59<02:11, 26.38s/it]

year 1999 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [05:16<01:35, 23.77s/it]

year 1999 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [05:19<00:52, 17.45s/it]

year 1999 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [05:20<00:25, 12.60s/it]

year 1999 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [05:22<00:09,  9.17s/it]

year 1999 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:22<00:00,  6.67s/it]

year 1999 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:22<00:00, 15.37s/it]

  done year 1999: 409157 images
  Checkpoint saved: 7 tickers done, 2777540 images

[I5/R5] build year: 2000

year 2000 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2000 chunks:   5%|███▏                                                                | 1/21 [00:15<05:16, 15.84s/it]

year 2000 chunks:  10%|██████▍                                                             | 2/21 [00:19<02:41,  8.51s/it]

year 2000 chunks:  14%|█████████▋                                                          | 3/21 [00:20<01:37,  5.42s/it]

year 2000 chunks:  19%|████████████▉                                                       | 4/21 [00:23<01:10,  4.12s/it]

year 2000 chunks:  24%|████████████████▏                                                   | 5/21 [00:32<01:34,  5.90s/it]

year 2000 chunks:  29%|███████████████████▍                                                | 6/21 [00:53<02:47, 11.19s/it]

year 2000 chunks:  33%|██████████████████████▋                                             | 7/21 [01:14<03:22, 14.47s/it]

year 2000 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:35<03:31, 16.29s/it]

year 2000 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:51<03:17, 16.43s/it]

year 2000 chunks:  48%|███████████████████████████████▉                                   | 10/21 [02:09<03:06, 16.93s/it]

year 2000 chunks:  52%|███████████████████████████████████                                | 11/21 [02:29<02:56, 17.63s/it]

year 2000 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [02:46<02:38, 17.65s/it]

year 2000 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [03:06<02:26, 18.36s/it]

year 2000 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [03:32<02:25, 20.73s/it]

year 2000 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [03:58<02:12, 22.09s/it]

year 2000 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [04:27<02:01, 24.36s/it]

year 2000 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [04:56<01:43, 25.76s/it]

year 2000 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [05:05<01:01, 20.53s/it]

year 2000 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [05:06<00:29, 14.75s/it]

year 2000 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [05:07<00:10, 10.66s/it]

year 2000 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:08<00:00,  7.71s/it]

year 2000 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [05:08<00:00, 14.69s/it]

  done year 2000: 399715 images
  Checkpoint saved: 8 tickers done, 3177255 images

[I5/R5] build year: 2001

year 2001 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2001 chunks:   5%|███▏                                                                | 1/21 [00:14<04:41, 14.06s/it]

year 2001 chunks:  10%|██████▍                                                             | 2/21 [00:17<02:25,  7.67s/it]

year 2001 chunks:  14%|█████████▋                                                          | 3/21 [00:18<01:29,  4.94s/it]

year 2001 chunks:  19%|████████████▉                                                       | 4/21 [00:20<01:03,  3.75s/it]

year 2001 chunks:  24%|████████████████▏                                                   | 5/21 [00:29<01:26,  5.41s/it]

year 2001 chunks:  29%|███████████████████▍                                                | 6/21 [00:48<02:32, 10.18s/it]

year 2001 chunks:  33%|██████████████████████▋                                             | 7/21 [01:08<03:04, 13.21s/it]

year 2001 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:26<03:13, 14.85s/it]

year 2001 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:41<02:59, 14.98s/it]

year 2001 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:57<02:49, 15.37s/it]

year 2001 chunks:  52%|███████████████████████████████████                                | 11/21 [02:20<02:54, 17.45s/it]

year 2001 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [02:35<02:30, 16.77s/it]

year 2001 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:52<02:14, 16.79s/it]

year 2001 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [03:10<01:59, 17.13s/it]

year 2001 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [03:30<01:49, 18.21s/it]

year 2001 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [03:56<01:42, 20.43s/it]

year 2001 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [04:25<01:32, 23.13s/it]

year 2001 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [04:45<01:06, 22.02s/it]

year 2001 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [04:46<00:31, 15.82s/it]

year 2001 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [04:47<00:11, 11.39s/it]

year 2001 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:48<00:00,  8.21s/it]

year 2001 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:48<00:00, 13.74s/it]

  done year 2001: 365125 images
  Checkpoint saved: 9 tickers done, 3542380 images

[I5/R5] build year: 2002

year 2002 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2002 chunks:   5%|███▏                                                                | 1/21 [00:12<04:14, 12.75s/it]

year 2002 chunks:  10%|██████▍                                                             | 2/21 [00:15<02:12,  6.99s/it]

year 2002 chunks:  14%|█████████▋                                                          | 3/21 [00:17<01:20,  4.50s/it]

year 2002 chunks:  19%|████████████▉                                                       | 4/21 [00:19<00:58,  3.43s/it]

year 2002 chunks:  24%|████████████████▏                                                   | 5/21 [00:26<01:18,  4.91s/it]

year 2002 chunks:  29%|███████████████████▍                                                | 6/21 [00:44<02:19,  9.32s/it]

year 2002 chunks:  33%|██████████████████████▋                                             | 7/21 [01:02<02:51, 12.27s/it]

year 2002 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:19<02:59, 13.82s/it]

year 2002 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:39<03:05, 15.47s/it]

year 2002 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:53<02:47, 15.21s/it]

year 2002 chunks:  52%|███████████████████████████████████                                | 11/21 [02:08<02:32, 15.24s/it]

year 2002 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [02:22<02:12, 14.71s/it]

year 2002 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:37<01:57, 14.73s/it]

year 2002 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:52<01:44, 14.92s/it]

year 2002 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [03:10<01:34, 15.79s/it]

year 2002 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [03:32<01:28, 17.76s/it]

year 2002 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [03:57<01:19, 19.96s/it]

year 2002 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [04:24<01:06, 22.03s/it]

year 2002 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [04:27<00:32, 16.18s/it]

year 2002 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [04:28<00:11, 11.62s/it]

year 2002 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:28<00:00,  8.35s/it]

year 2002 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:28<00:00, 12.81s/it]

  done year 2002: 341570 images
  Checkpoint saved: 10 tickers done, 3883950 images

[I5/R5] build year: 2003

year 2003 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2003 chunks:   5%|███▏                                                                | 1/21 [00:12<04:01, 12.07s/it]

year 2003 chunks:  10%|██████▍                                                             | 2/21 [00:14<02:06,  6.66s/it]

year 2003 chunks:  14%|█████████▋                                                          | 3/21 [00:16<01:17,  4.32s/it]

year 2003 chunks:  19%|████████████▉                                                       | 4/21 [00:18<00:57,  3.37s/it]

year 2003 chunks:  24%|████████████████▏                                                   | 5/21 [00:25<01:16,  4.76s/it]

year 2003 chunks:  29%|███████████████████▍                                                | 6/21 [00:43<02:17,  9.17s/it]

year 2003 chunks:  33%|██████████████████████▋                                             | 7/21 [01:00<02:46, 11.92s/it]

year 2003 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:17<02:53, 13.31s/it]

year 2003 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:30<02:39, 13.29s/it]

year 2003 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:50<02:48, 15.33s/it]

year 2003 chunks:  52%|███████████████████████████████████                                | 11/21 [02:04<02:30, 15.01s/it]

year 2003 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [02:16<02:07, 14.17s/it]

year 2003 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:30<01:51, 13.98s/it]

year 2003 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:44<01:37, 13.96s/it]

year 2003 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [03:00<01:27, 14.63s/it]

year 2003 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [03:20<01:21, 16.24s/it]

year 2003 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [03:41<01:11, 17.78s/it]

year 2003 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [04:10<01:03, 21.15s/it]

year 2003 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [04:19<00:34, 17.27s/it]

year 2003 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [04:19<00:12, 12.35s/it]

year 2003 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:20<00:00,  8.86s/it]

year 2003 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:20<00:00, 12.41s/it]

  done year 2003: 327096 images
  Checkpoint saved: 11 tickers done, 4211046 images

[I5/R5] build year: 2004

year 2004 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2004 chunks:   5%|███▏                                                                | 1/21 [00:11<03:45, 11.28s/it]

year 2004 chunks:  10%|██████▍                                                             | 2/21 [00:14<01:59,  6.29s/it]

year 2004 chunks:  14%|█████████▋                                                          | 3/21 [00:15<01:13,  4.11s/it]

year 2004 chunks:  19%|████████████▉                                                       | 4/21 [00:17<00:54,  3.21s/it]

year 2004 chunks:  24%|████████████████▏                                                   | 5/21 [00:24<01:13,  4.57s/it]

year 2004 chunks:  29%|███████████████████▍                                                | 6/21 [00:41<02:13,  8.87s/it]

year 2004 chunks:  33%|██████████████████████▋                                             | 7/21 [00:58<02:42, 11.58s/it]

year 2004 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:14<02:47, 12.85s/it]

year 2004 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:26<02:32, 12.69s/it]

year 2004 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:39<02:21, 12.84s/it]

year 2004 chunks:  52%|███████████████████████████████████                                | 11/21 [01:53<02:10, 13.01s/it]

year 2004 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [02:04<01:52, 12.45s/it]

year 2004 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:17<01:40, 12.50s/it]

year 2004 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:36<01:41, 14.55s/it]

year 2004 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:51<01:28, 14.68s/it]

year 2004 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [03:09<01:18, 15.74s/it]

year 2004 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [03:28<01:07, 16.82s/it]

year 2004 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [03:56<01:00, 20.21s/it]

year 2004 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [04:17<00:40, 20.19s/it]

year 2004 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [04:18<00:14, 14.59s/it]

year 2004 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:19<00:00, 10.42s/it]

year 2004 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:19<00:00, 12.35s/it]

  done year 2004: 333895 images
  Checkpoint saved: 12 tickers done, 4544941 images

[I5/R5] build year: 2005

year 2005 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2005 chunks:   5%|███▏                                                                | 1/21 [00:10<03:26, 10.32s/it]

year 2005 chunks:  10%|██████▍                                                             | 2/21 [00:12<01:50,  5.79s/it]

year 2005 chunks:  14%|█████████▋                                                          | 3/21 [00:14<01:08,  3.82s/it]

year 2005 chunks:  19%|████████████▉                                                       | 4/21 [00:16<00:51,  3.01s/it]

year 2005 chunks:  24%|████████████████▏                                                   | 5/21 [00:23<01:10,  4.39s/it]

year 2005 chunks:  29%|███████████████████▍                                                | 6/21 [00:39<02:07,  8.48s/it]

year 2005 chunks:  33%|██████████████████████▋                                             | 7/21 [00:55<02:34, 11.03s/it]

year 2005 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:10<02:38, 12.18s/it]

year 2005 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:21<02:24, 12.00s/it]

year 2005 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:34<02:13, 12.11s/it]

year 2005 chunks:  52%|███████████████████████████████████                                | 11/21 [01:46<02:01, 12.20s/it]

year 2005 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [01:56<01:44, 11.60s/it]

year 2005 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:08<01:32, 11.58s/it]

year 2005 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:20<01:22, 11.72s/it]

year 2005 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:34<01:14, 12.34s/it]

year 2005 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:50<01:08, 13.62s/it]

year 2005 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [03:08<00:58, 14.67s/it]

year 2005 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [03:40<01:00, 20.08s/it]

year 2005 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [04:11<00:46, 23.34s/it]

year 2005 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [04:16<00:17, 17.89s/it]

year 2005 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:17<00:00, 12.73s/it]

year 2005 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:17<00:00, 12.26s/it]

  done year 2005: 329392 images
  Checkpoint saved: 13 tickers done, 4874333 images

[I5/R5] build year: 2006

year 2006 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2006 chunks:   5%|███▏                                                                | 1/21 [00:09<03:13,  9.68s/it]

year 2006 chunks:  10%|██████▍                                                             | 2/21 [00:12<01:42,  5.41s/it]

year 2006 chunks:  14%|█████████▋                                                          | 3/21 [00:13<01:04,  3.59s/it]

year 2006 chunks:  19%|████████████▉                                                       | 4/21 [00:15<00:48,  2.83s/it]

year 2006 chunks:  24%|████████████████▏                                                   | 5/21 [00:21<01:06,  4.18s/it]

year 2006 chunks:  29%|███████████████████▍                                                | 6/21 [00:37<02:01,  8.13s/it]

year 2006 chunks:  33%|██████████████████████▋                                             | 7/21 [00:53<02:28, 10.63s/it]

year 2006 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:06<02:30, 11.59s/it]

year 2006 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:17<02:16, 11.38s/it]

year 2006 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:29<02:06, 11.50s/it]

year 2006 chunks:  52%|███████████████████████████████████                                | 11/21 [01:41<01:55, 11.57s/it]

year 2006 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [01:51<01:38, 10.98s/it]

year 2006 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:01<01:27, 10.89s/it]

year 2006 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:12<01:16, 10.94s/it]

year 2006 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:25<01:09, 11.51s/it]

year 2006 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:40<01:03, 12.68s/it]

year 2006 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:56<00:54, 13.63s/it]

year 2006 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [03:21<00:50, 16.82s/it]

year 2006 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:54<00:43, 21.85s/it]

year 2006 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [04:11<00:20, 20.37s/it]

year 2006 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:12<00:00, 14.62s/it]

year 2006 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:12<00:00, 12.04s/it]

  done year 2006: 328180 images
  Checkpoint saved: 14 tickers done, 5202513 images

[I5/R5] build year: 2007

year 2007 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2007 chunks:   5%|███▏                                                                | 1/21 [00:09<03:02,  9.13s/it]

year 2007 chunks:  10%|██████▍                                                             | 2/21 [00:11<01:36,  5.07s/it]

year 2007 chunks:  14%|█████████▋                                                          | 3/21 [00:12<01:01,  3.41s/it]

year 2007 chunks:  19%|████████████▉                                                       | 4/21 [00:14<00:45,  2.66s/it]

year 2007 chunks:  24%|████████████████▏                                                   | 5/21 [00:20<01:04,  4.00s/it]

year 2007 chunks:  29%|███████████████████▍                                                | 6/21 [00:36<01:57,  7.85s/it]

year 2007 chunks:  33%|██████████████████████▋                                             | 7/21 [00:51<02:22, 10.20s/it]

year 2007 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:11<02:55, 13.49s/it]

year 2007 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:22<02:30, 12.55s/it]

year 2007 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:33<02:13, 12.10s/it]

year 2007 chunks:  52%|███████████████████████████████████                                | 11/21 [01:44<01:57, 11.74s/it]

year 2007 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [01:52<01:37, 10.84s/it]

year 2007 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:02<01:23, 10.46s/it]

year 2007 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:12<01:12, 10.29s/it]

year 2007 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:23<01:04, 10.69s/it]

year 2007 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:38<00:58, 11.79s/it]

year 2007 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:52<00:50, 12.60s/it]

year 2007 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [03:15<00:46, 15.50s/it]

year 2007 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:46<00:40, 20.28s/it]

year 2007 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [04:15<00:22, 22.91s/it]

year 2007 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:19<00:00, 17.11s/it]

year 2007 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:19<00:00, 12.34s/it]

  done year 2007: 327498 images
  Checkpoint saved: 15 tickers done, 5530011 images

[I5/R5] build year: 2008

year 2008 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2008 chunks:   5%|███▏                                                                | 1/21 [00:08<02:51,  8.59s/it]

year 2008 chunks:  10%|██████▍                                                             | 2/21 [00:10<01:32,  4.85s/it]

year 2008 chunks:  14%|█████████▋                                                          | 3/21 [00:12<00:58,  3.26s/it]

year 2008 chunks:  19%|████████████▉                                                       | 4/21 [00:13<00:43,  2.57s/it]

year 2008 chunks:  24%|████████████████▏                                                   | 5/21 [00:19<01:00,  3.79s/it]

year 2008 chunks:  29%|███████████████████▍                                                | 6/21 [00:34<01:51,  7.42s/it]

year 2008 chunks:  33%|██████████████████████▋                                             | 7/21 [00:48<02:14,  9.63s/it]

year 2008 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:00<02:14, 10.31s/it]

year 2008 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:09<02:01, 10.15s/it]

year 2008 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:19<01:51, 10.12s/it]

year 2008 chunks:  52%|███████████████████████████████████                                | 11/21 [01:30<01:41, 10.20s/it]

year 2008 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [01:38<01:26,  9.62s/it]

year 2008 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [01:47<01:14,  9.31s/it]

year 2008 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [01:56<01:04,  9.16s/it]

year 2008 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:06<00:57,  9.56s/it]

year 2008 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:19<00:53, 10.64s/it]

year 2008 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:32<00:45, 11.40s/it]

year 2008 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [02:53<00:42, 14.26s/it]

year 2008 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:30<00:42, 21.07s/it]

year 2008 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [04:02<00:24, 24.30s/it]

year 2008 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:13<00:00, 20.26s/it]

year 2008 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [04:13<00:00, 12.06s/it]

  done year 2008: 316997 images
  Checkpoint saved: 16 tickers done, 5847008 images

[I5/R5] build year: 2009

year 2009 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2009 chunks:   5%|███▏                                                                | 1/21 [00:08<02:43,  8.16s/it]

year 2009 chunks:  10%|██████▍                                                             | 2/21 [00:10<01:33,  4.91s/it]

year 2009 chunks:  14%|█████████▋                                                          | 3/21 [00:12<00:59,  3.28s/it]

year 2009 chunks:  19%|████████████▉                                                       | 4/21 [00:13<00:44,  2.60s/it]

year 2009 chunks:  24%|████████████████▏                                                   | 5/21 [00:19<00:58,  3.68s/it]

year 2009 chunks:  29%|███████████████████▍                                                | 6/21 [00:32<01:45,  7.05s/it]

year 2009 chunks:  33%|██████████████████████▋                                             | 7/21 [00:46<02:07,  9.14s/it]

year 2009 chunks:  38%|█████████████████████████▉                                          | 8/21 [00:57<02:06,  9.75s/it]

year 2009 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:06<01:54,  9.54s/it]

year 2009 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:15<01:44,  9.53s/it]

year 2009 chunks:  52%|███████████████████████████████████                                | 11/21 [01:25<01:36,  9.63s/it]

year 2009 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [01:33<01:21,  9.00s/it]

year 2009 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [01:41<01:09,  8.65s/it]

year 2009 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [01:49<00:59,  8.45s/it]

year 2009 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [01:58<00:53,  8.84s/it]

year 2009 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:11<00:49,  9.81s/it]

year 2009 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:23<00:41, 10.49s/it]

year 2009 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [02:42<00:39, 13.16s/it]

year 2009 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:08<00:33, 16.99s/it]

year 2009 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:37<00:20, 20.56s/it]

year 2009 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:53<00:00, 19.31s/it]

year 2009 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:53<00:00, 11.13s/it]

  done year 2009: 304209 images
  Checkpoint saved: 17 tickers done, 6151217 images

[I5/R5] build year: 2010

year 2010 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2010 chunks:   5%|███▏                                                                | 1/21 [00:07<02:36,  7.81s/it]

year 2010 chunks:  10%|██████▍                                                             | 2/21 [00:13<01:59,  6.27s/it]

year 2010 chunks:  14%|█████████▋                                                          | 3/21 [00:14<01:11,  3.98s/it]

year 2010 chunks:  19%|████████████▉                                                       | 4/21 [00:16<00:53,  3.14s/it]

year 2010 chunks:  24%|████████████████▏                                                   | 5/21 [00:21<01:03,  3.94s/it]

year 2010 chunks:  29%|███████████████████▍                                                | 6/21 [00:34<01:43,  6.92s/it]

year 2010 chunks:  33%|██████████████████████▋                                             | 7/21 [00:46<02:02,  8.75s/it]

year 2010 chunks:  38%|█████████████████████████▉                                          | 8/21 [00:57<02:00,  9.30s/it]

year 2010 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:05<01:47,  8.97s/it]

year 2010 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:14<01:38,  8.96s/it]

year 2010 chunks:  52%|███████████████████████████████████                                | 11/21 [01:23<01:30,  9.06s/it]

year 2010 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [01:30<01:15,  8.41s/it]

year 2010 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [01:37<01:04,  8.09s/it]

year 2010 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [01:45<00:54,  7.81s/it]

year 2010 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [01:54<00:48,  8.15s/it]

year 2010 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:04<00:44,  8.99s/it]

year 2010 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:15<00:38,  9.51s/it]

year 2010 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [02:42<00:44, 14.84s/it]

year 2010 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:06<00:34, 17.42s/it]

year 2010 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:32<00:20, 20.02s/it]

year 2010 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:54<00:00, 20.50s/it]

year 2010 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:54<00:00, 11.15s/it]

  done year 2010: 292821 images
  Checkpoint saved: 18 tickers done, 6444038 images

[I5/R5] build year: 2011

year 2011 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2011 chunks:   5%|███▏                                                                | 1/21 [00:07<02:32,  7.61s/it]

year 2011 chunks:  10%|██████▍                                                             | 2/21 [00:21<03:29, 11.05s/it]

year 2011 chunks:  14%|█████████▋                                                          | 3/21 [00:22<01:58,  6.57s/it]

year 2011 chunks:  19%|████████████▉                                                       | 4/21 [00:24<01:20,  4.74s/it]

year 2011 chunks:  24%|████████████████▏                                                   | 5/21 [00:29<01:18,  4.89s/it]

year 2011 chunks:  29%|███████████████████▍                                                | 6/21 [00:41<01:50,  7.40s/it]

year 2011 chunks:  33%|██████████████████████▋                                             | 7/21 [00:53<02:05,  8.95s/it]

year 2011 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:03<02:00,  9.28s/it]

year 2011 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:11<01:46,  8.85s/it]

year 2011 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:20<01:36,  8.77s/it]

year 2011 chunks:  52%|███████████████████████████████████                                | 11/21 [01:29<01:28,  8.83s/it]

year 2011 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [01:35<01:13,  8.17s/it]

year 2011 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [01:42<01:02,  7.79s/it]

year 2011 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [01:49<00:52,  7.48s/it]

year 2011 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [01:58<00:46,  7.79s/it]

year 2011 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:08<00:42,  8.48s/it]

year 2011 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:18<00:35,  8.93s/it]

year 2011 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [02:35<00:34, 11.56s/it]

year 2011 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [02:57<00:29, 14.71s/it]

year 2011 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:22<00:17, 17.55s/it]

year 2011 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:44<00:00, 18.93s/it]

year 2011 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:44<00:00, 10.68s/it]

  done year 2011: 290081 images
  Checkpoint saved: 19 tickers done, 6734119 images

[I5/R5] build year: 2012

year 2012 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2012 chunks:   5%|███▏                                                                | 1/21 [00:07<02:27,  7.39s/it]

year 2012 chunks:  10%|██████▍                                                             | 2/21 [00:29<05:08, 16.26s/it]

year 2012 chunks:  14%|█████████▋                                                          | 3/21 [00:32<02:57,  9.86s/it]

year 2012 chunks:  19%|████████████▉                                                       | 4/21 [00:34<01:54,  6.73s/it]

year 2012 chunks:  24%|████████████████▏                                                   | 5/21 [00:39<01:37,  6.11s/it]

year 2012 chunks:  29%|███████████████████▍                                                | 6/21 [00:51<02:02,  8.14s/it]

year 2012 chunks:  33%|██████████████████████▋                                             | 7/21 [01:02<02:10,  9.31s/it]

year 2012 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:12<02:02,  9.42s/it]

year 2012 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:19<01:45,  8.80s/it]

year 2012 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:28<01:34,  8.60s/it]

year 2012 chunks:  52%|███████████████████████████████████                                | 11/21 [01:36<01:25,  8.57s/it]

year 2012 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [01:42<01:11,  7.89s/it]

year 2012 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [01:49<01:00,  7.55s/it]

year 2012 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [01:55<00:50,  7.16s/it]

year 2012 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:03<00:44,  7.37s/it]

year 2012 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:13<00:39,  7.96s/it]

year 2012 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:22<00:33,  8.37s/it]

year 2012 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [02:49<00:41, 13.91s/it]

year 2012 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:09<00:31, 15.81s/it]

year 2012 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:31<00:17, 17.64s/it]

year 2012 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:51<00:00, 18.39s/it]

year 2012 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:51<00:00, 11.03s/it]

  done year 2012: 285773 images
  Checkpoint saved: 20 tickers done, 7019892 images

[I5/R5] build year: 2013

year 2013 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2013 chunks:   5%|███▏                                                                | 1/21 [00:06<02:18,  6.92s/it]

year 2013 chunks:  10%|██████▍                                                             | 2/21 [00:35<06:10, 19.53s/it]

year 2013 chunks:  14%|█████████▋                                                          | 3/21 [00:42<04:11, 14.00s/it]

year 2013 chunks:  19%|████████████▉                                                       | 4/21 [00:44<02:34,  9.11s/it]

year 2013 chunks:  24%|████████████████▏                                                   | 5/21 [00:49<02:00,  7.56s/it]

year 2013 chunks:  29%|███████████████████▍                                                | 6/21 [01:00<02:12,  8.86s/it]

year 2013 chunks:  33%|██████████████████████▋                                             | 7/21 [01:11<02:14,  9.60s/it]

year 2013 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:20<02:03,  9.49s/it]

year 2013 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:27<01:43,  8.66s/it]

year 2013 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:35<01:32,  8.38s/it]

year 2013 chunks:  52%|███████████████████████████████████                                | 11/21 [01:43<01:22,  8.28s/it]

year 2013 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [01:49<01:08,  7.57s/it]

year 2013 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [01:55<00:57,  7.22s/it]

year 2013 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:01<00:47,  6.81s/it]

year 2013 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:09<00:41,  6.96s/it]

year 2013 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:17<00:37,  7.50s/it]

year 2013 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:26<00:31,  7.91s/it]

year 2013 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [02:41<00:30, 10.09s/it]

year 2013 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:00<00:25, 12.74s/it]

year 2013 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:21<00:15, 15.01s/it]

year 2013 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:39<00:00, 16.02s/it]

year 2013 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:39<00:00, 10.45s/it]

  done year 2013: 285425 images
  Checkpoint saved: 21 tickers done, 7305317 images

[I5/R5] build year: 2014

year 2014 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2014 chunks:   5%|███▏                                                                | 1/21 [00:06<02:09,  6.50s/it]

year 2014 chunks:  10%|██████▍                                                             | 2/21 [00:35<06:11, 19.57s/it]

year 2014 chunks:  14%|█████████▋                                                          | 3/21 [00:55<05:57, 19.85s/it]

year 2014 chunks:  19%|████████████▉                                                       | 4/21 [00:57<03:37, 12.81s/it]

year 2014 chunks:  24%|████████████████▏                                                   | 5/21 [01:02<02:37,  9.85s/it]

year 2014 chunks:  29%|███████████████████▍                                                | 6/21 [01:12<02:32, 10.20s/it]

year 2014 chunks:  33%|██████████████████████▋                                             | 7/21 [01:23<02:25, 10.36s/it]

year 2014 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:32<02:09,  9.94s/it]

year 2014 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:39<01:46,  8.84s/it]

year 2014 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:46<01:32,  8.39s/it]

year 2014 chunks:  52%|███████████████████████████████████                                | 11/21 [01:53<01:21,  8.13s/it]

year 2014 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [01:59<01:06,  7.43s/it]

year 2014 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:05<00:56,  7.04s/it]

year 2014 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:11<00:46,  6.60s/it]

year 2014 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:18<00:40,  6.72s/it]

year 2014 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:26<00:35,  7.19s/it]

year 2014 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:35<00:30,  7.56s/it]

year 2014 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [02:49<00:28,  9.61s/it]

year 2014 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:07<00:24, 12.11s/it]

year 2014 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:26<00:14, 14.29s/it]

year 2014 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:54<00:00, 18.41s/it]

year 2014 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:54<00:00, 11.19s/it]

  done year 2014: 293955 images
  Checkpoint saved: 22 tickers done, 7599272 images

[I5/R5] build year: 2015

year 2015 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2015 chunks:   5%|███▏                                                                | 1/21 [00:06<02:09,  6.47s/it]

year 2015 chunks:  10%|██████▍                                                             | 2/21 [00:34<05:58, 18.87s/it]

year 2015 chunks:  14%|█████████▋                                                          | 3/21 [01:05<07:22, 24.60s/it]

year 2015 chunks:  19%|████████████▉                                                       | 4/21 [01:09<04:43, 16.65s/it]

year 2015 chunks:  24%|████████████████▏                                                   | 5/21 [01:14<03:17, 12.33s/it]

year 2015 chunks:  29%|███████████████████▍                                                | 6/21 [01:25<02:55, 11.73s/it]

year 2015 chunks:  33%|██████████████████████▋                                             | 7/21 [01:35<02:39, 11.37s/it]

year 2015 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:44<02:17, 10.55s/it]

year 2015 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:50<01:49,  9.11s/it]

year 2015 chunks:  48%|███████████████████████████████▉                                   | 10/21 [01:57<01:33,  8.52s/it]

year 2015 chunks:  52%|███████████████████████████████████                                | 11/21 [02:05<01:21,  8.18s/it]

year 2015 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [02:10<01:06,  7.38s/it]

year 2015 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:16<00:55,  6.94s/it]

year 2015 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:21<00:45,  6.46s/it]

year 2015 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:28<00:39,  6.56s/it]

year 2015 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:36<00:35,  7.03s/it]

year 2015 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:44<00:29,  7.29s/it]

year 2015 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [02:58<00:27,  9.19s/it]

year 2015 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:15<00:23, 11.52s/it]

year 2015 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:33<00:13, 13.52s/it]

year 2015 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:49<00:00, 14.21s/it]

year 2015 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:49<00:00, 10.92s/it]

  done year 2015: 304120 images
  Checkpoint saved: 23 tickers done, 7903392 images

[I5/R5] build year: 2016

year 2016 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2016 chunks:   5%|███▏                                                                | 1/21 [00:06<02:03,  6.15s/it]

year 2016 chunks:  10%|██████▍                                                             | 2/21 [00:31<05:25, 17.16s/it]

year 2016 chunks:  14%|█████████▋                                                          | 3/21 [01:04<07:21, 24.52s/it]

year 2016 chunks:  19%|████████████▉                                                       | 4/21 [01:16<05:33, 19.60s/it]

year 2016 chunks:  24%|████████████████▏                                                   | 5/21 [01:20<03:46, 14.17s/it]

year 2016 chunks:  29%|███████████████████▍                                                | 6/21 [01:30<03:10, 12.71s/it]

year 2016 chunks:  33%|██████████████████████▋                                             | 7/21 [01:40<02:44, 11.78s/it]

year 2016 chunks:  38%|█████████████████████████▉                                          | 8/21 [01:48<02:18, 10.62s/it]

year 2016 chunks:  43%|█████████████████████████████▏                                      | 9/21 [01:54<01:47,  8.98s/it]

year 2016 chunks:  48%|███████████████████████████████▉                                   | 10/21 [02:00<01:31,  8.30s/it]

year 2016 chunks:  52%|███████████████████████████████████                                | 11/21 [02:07<01:18,  7.86s/it]

year 2016 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [02:12<01:03,  7.02s/it]

year 2016 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:18<00:52,  6.56s/it]

year 2016 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:23<00:42,  6.12s/it]

year 2016 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:29<00:37,  6.20s/it]

year 2016 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:37<00:33,  6.60s/it]

year 2016 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:44<00:27,  6.84s/it]

year 2016 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [02:57<00:25,  8.56s/it]

year 2016 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:12<00:21, 10.67s/it]

year 2016 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:29<00:12, 12.45s/it]

year 2016 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:43<00:00, 13.01s/it]

year 2016 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:43<00:00, 10.66s/it]

  done year 2016: 292898 images
  Checkpoint saved: 24 tickers done, 8196290 images

[I5/R5] build year: 2017

year 2017 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2017 chunks:   5%|███▏                                                                | 1/21 [00:05<01:59,  5.96s/it]

year 2017 chunks:  10%|██████▍                                                             | 2/21 [00:28<05:04, 16.00s/it]

year 2017 chunks:  14%|█████████▋                                                          | 3/21 [01:00<06:51, 22.86s/it]

year 2017 chunks:  19%|████████████▉                                                       | 4/21 [01:33<07:42, 27.22s/it]

year 2017 chunks:  24%|████████████████▏                                                   | 5/21 [01:39<05:09, 19.32s/it]

year 2017 chunks:  29%|███████████████████▍                                                | 6/21 [01:48<04:00, 16.03s/it]

year 2017 chunks:  33%|██████████████████████▋                                             | 7/21 [01:58<03:14, 13.91s/it]

year 2017 chunks:  38%|█████████████████████████▉                                          | 8/21 [02:06<02:34, 11.90s/it]

year 2017 chunks:  43%|█████████████████████████████▏                                      | 9/21 [02:11<01:57,  9.78s/it]

year 2017 chunks:  48%|███████████████████████████████▉                                   | 10/21 [02:17<01:36,  8.76s/it]

year 2017 chunks:  52%|███████████████████████████████████                                | 11/21 [02:24<01:21,  8.11s/it]

year 2017 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [02:29<01:04,  7.12s/it]

year 2017 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:34<00:52,  6.58s/it]

year 2017 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:39<00:42,  6.08s/it]

year 2017 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:45<00:36,  6.10s/it]

year 2017 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:52<00:32,  6.42s/it]

year 2017 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:59<00:26,  6.59s/it]

year 2017 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [03:11<00:24,  8.16s/it]

year 2017 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:26<00:20, 10.14s/it]

year 2017 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:41<00:11, 11.73s/it]

year 2017 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:55<00:00, 12.21s/it]

year 2017 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:55<00:00, 11.19s/it]

  done year 2017: 290768 images
  Checkpoint saved: 25 tickers done, 8487058 images

[I5/R5] build year: 2018

year 2018 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2018 chunks:   5%|███▏                                                                | 1/21 [00:05<01:55,  5.80s/it]

year 2018 chunks:  10%|██████▍                                                             | 2/21 [00:27<04:44, 14.97s/it]

year 2018 chunks:  14%|█████████▋                                                          | 3/21 [00:55<06:22, 21.22s/it]

year 2018 chunks:  19%|████████████▉                                                       | 4/21 [01:25<07:00, 24.74s/it]

year 2018 chunks:  24%|████████████████▏                                                   | 5/21 [01:35<05:09, 19.32s/it]

year 2018 chunks:  29%|███████████████████▍                                                | 6/21 [01:44<03:57, 15.87s/it]

year 2018 chunks:  33%|██████████████████████▋                                             | 7/21 [01:54<03:11, 13.71s/it]

year 2018 chunks:  38%|█████████████████████████▉                                          | 8/21 [02:01<02:31, 11.66s/it]

year 2018 chunks:  43%|█████████████████████████████▏                                      | 9/21 [02:06<01:54,  9.53s/it]

year 2018 chunks:  48%|███████████████████████████████▉                                   | 10/21 [02:12<01:33,  8.47s/it]

year 2018 chunks:  52%|███████████████████████████████████                                | 11/21 [02:18<01:18,  7.85s/it]

year 2018 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [02:23<01:01,  6.87s/it]

year 2018 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:28<00:50,  6.31s/it]

year 2018 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:33<00:40,  5.85s/it]

year 2018 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:39<00:35,  5.84s/it]

year 2018 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:45<00:30,  6.12s/it]

year 2018 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:52<00:25,  6.27s/it]

year 2018 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [03:03<00:23,  7.72s/it]

year 2018 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:17<00:19,  9.58s/it]

year 2018 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:31<00:10, 10.97s/it]

year 2018 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:44<00:00, 11.46s/it]

year 2018 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:44<00:00, 10.68s/it]

  done year 2018: 294063 images
  Checkpoint saved: 26 tickers done, 8781121 images

[I5/R5] build year: 2019

year 2019 chunks:   0%|                                                                            | 0/21 [00:00<?, ?it/s]

year 2019 chunks:   5%|███▏                                                                | 1/21 [00:05<01:50,  5.55s/it]

year 2019 chunks:  10%|██████▍                                                             | 2/21 [00:25<04:24, 13.92s/it]

year 2019 chunks:  14%|█████████▋                                                          | 3/21 [00:51<05:53, 19.64s/it]

year 2019 chunks:  19%|████████████▉                                                       | 4/21 [01:22<06:51, 24.19s/it]

year 2019 chunks:  24%|████████████████▏                                                   | 5/21 [01:41<05:56, 22.26s/it]

year 2019 chunks:  29%|███████████████████▍                                                | 6/21 [01:50<04:24, 17.66s/it]

year 2019 chunks:  33%|██████████████████████▋                                             | 7/21 [01:59<03:27, 14.82s/it]

year 2019 chunks:  38%|█████████████████████████▉                                          | 8/21 [02:06<02:40, 12.34s/it]

year 2019 chunks:  43%|█████████████████████████████▏                                      | 9/21 [02:11<01:59,  9.93s/it]

year 2019 chunks:  48%|███████████████████████████████▉                                   | 10/21 [02:16<01:34,  8.60s/it]

year 2019 chunks:  52%|███████████████████████████████████                                | 11/21 [02:22<01:18,  7.85s/it]

year 2019 chunks:  57%|██████████████████████████████████████▎                            | 12/21 [02:27<01:00,  6.77s/it]

year 2019 chunks:  62%|█████████████████████████████████████████▍                         | 13/21 [02:32<00:49,  6.18s/it]

year 2019 chunks:  67%|████████████████████████████████████████████▋                      | 14/21 [02:36<00:39,  5.69s/it]

year 2019 chunks:  71%|███████████████████████████████████████████████▊                   | 15/21 [02:42<00:33,  5.66s/it]

year 2019 chunks:  76%|███████████████████████████████████████████████████                | 16/21 [02:48<00:29,  5.82s/it]

year 2019 chunks:  81%|██████████████████████████████████████████████████████▏            | 17/21 [02:54<00:23,  5.95s/it]

year 2019 chunks:  86%|█████████████████████████████████████████████████████████▍         | 18/21 [03:04<00:21,  7.28s/it]

year 2019 chunks:  90%|████████████████████████████████████████████████████████████▌      | 19/21 [03:18<00:18,  9.02s/it]

year 2019 chunks:  95%|███████████████████████████████████████████████████████████████▊   | 20/21 [03:31<00:10, 10.26s/it]

year 2019 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:56<00:00, 14.66s/it]

year 2019 chunks: 100%|███████████████████████████████████████████████████████████████████| 21/21 [03:56<00:00, 11.25s/it]

  done year 2019: 295232 images
  Checkpoint saved: 27 tickers done, 9076353 images
  Checkpoint saved: 27 tickers done, 9076353 images

總樣本數: 9076353
標籤分布: up=0.500, down=0.500

  Train+Val: 3177255  (up=0.478)
  Test     : 5899098  (up=0.511)

撌脣摮 data/training_data/US_1993_2020/I5R5S5_week/

In [4]:
I = 5
R = 5
Market = "US_1993_2020"

dataset_dir = f"data/training_data/{Market}/I{I}R{R}S{R}_week"

X_trainval = np.load(f"{dataset_dir}/X_trainval.npy")
y_trainval = np.load(f"{dataset_dir}/y_trainval.npy")

X_test = np.load(f"{dataset_dir}/X_test.npy")
y_test = np.load(f"{dataset_dir}/y_test.npy")

meta = pd.read_csv(f"{dataset_dir}/meta.csv")
meta_trainval = pd.read_csv(f"{dataset_dir}/meta_trainval.csv")
meta_test = pd.read_csv(f"{dataset_dir}/meta_test.csv")

print("X_trainval:", X_trainval.shape)
print("y_trainval:", y_trainval.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

print("meta_trainval:", meta_trainval.shape)
print("meta_test:", meta_test.shape)

display(meta.head())

X_trainval: (3177255, 32, 15)
y_trainval: (3177255,)
X_test: (5899098, 32, 15)
y_test: (5899098,)
meta_trainval: (3177255, 12)
meta_test: (5899098, 12)

,ticker,start_date,date,label_end_date,label,ret,I,R,sample_step,sample_freq,price_source,ending_date
0,10001,1993-01-14,1993-01-22,1993-02-09,0,-0.018170,5,5,5,week,crsp,1993-01-22
1,10001,1993-02-02,1993-02-12,1993-03-01,1,0.054209,5,5,5,week,crsp,1993-02-12
2,10001,1993-02-12,1993-02-26,1993-03-11,1,0.020092,5,5,5,week,crsp,1993-02-26
3,10001,1993-03-08,1993-03-12,1993-03-23,0,-0.052392,5,5,5,week,crsp,1993-03-12
4,10001,1993-03-25,1993-04-08,1993-04-19,1,0.044248,5,5,5,week,crsp,1993-04-08

In [5]:
import model
importlib.reload(model)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


RUN_SEEDS = list(range(10))
ENSEMBLE_DIR = f"models/{Market}/I{I}R{R}"
EPOCHS = 50
BATCH_SIZE = 256
VAL_RATIO = 0.3

ensemble_results = model.train_resplit_ensemble(
    X_trainval=X_trainval,
    y_trainval=y_trainval,
    I=I,
    R=R,
    seeds=RUN_SEEDS,
    save_dir=ENSEMBLE_DIR,
    Market=Market,
    val_ratio=VAL_RATIO,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    lr=1e-4,
    weight_decay=0,
    device=device,
)

Using device: cuda

ensemble runs:   0%|                                                                               | 0/10 [00:00<?, ?it/s]

ensemble runs:   0%|                                                                       | 0/10 [00:00<?, ?it/s, seed=0]

/home/iof_314707035/miniconda3/envs/reimage-price-trends/lib/python3.11/site-packages/torch/cuda/__init__.py:435: UserWarning:
    Found GPU0 NVIDIA GB10 which is of cuda capability 12.1.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (7.5) - (12.0)

  queued_call()

seed 0:   0%|                                                                                      | 0/50 [00:00<?, ?it/s]

seed 0:   0%|                     | 0/50 [03:59<?, ?it/s, best=54.58%, train_loss=0.6994, val_acc=54.58%, val_loss=0.6858]

seed 0:   2%|▏         | 1/50 [03:59<3:15:58, 239.96s/it, best=54.58%, train_loss=0.6994, val_acc=54.58%, val_loss=0.6858]

seed 0:   2%|▏         | 1/50 [07:58<3:15:58, 239.96s/it, best=54.92%, train_loss=0.6902, val_acc=54.92%, val_loss=0.6853]

seed 0:   4%|▍         | 2/50 [07:58<3:11:19, 239.15s/it, best=54.92%, train_loss=0.6902, val_acc=54.92%, val_loss=0.6853]

seed 0:   4%|▍         | 2/50 [11:55<3:11:19, 239.15s/it, best=54.92%, train_loss=0.6870, val_acc=54.86%, val_loss=0.6849]

seed 0:   6%|▌         | 3/50 [11:55<3:06:33, 238.16s/it, best=54.92%, train_loss=0.6870, val_acc=54.86%, val_loss=0.6849]

seed 0:   6%|▌         | 3/50 [15:55<3:06:33, 238.16s/it, best=54.94%, train_loss=0.6854, val_acc=54.94%, val_loss=0.6847]

seed 0:   8%|▊         | 4/50 [15:55<3:03:14, 239.00s/it, best=54.94%, train_loss=0.6854, val_acc=54.94%, val_loss=0.6847]

seed 0:   8%|▊         | 4/50 [19:43<3:03:14, 239.00s/it, best=55.02%, train_loss=0.6849, val_acc=55.02%, val_loss=0.6844]

seed 0:  10%|█         | 5/50 [19:43<2:56:19, 235.09s/it, best=55.02%, train_loss=0.6849, val_acc=55.02%, val_loss=0.6844]

seed 0:  10%|█         | 5/50 [23:45<2:56:19, 235.09s/it, best=55.03%, train_loss=0.6847, val_acc=55.03%, val_loss=0.6846]

seed 0:  12%|█▏        | 6/50 [23:45<2:54:05, 237.41s/it, best=55.03%, train_loss=0.6847, val_acc=55.03%, val_loss=0.6846]

seed 0:  12%|█▏        | 6/50 [27:48<2:54:05, 237.41s/it, best=55.05%, train_loss=0.6845, val_acc=55.05%, val_loss=0.6843]

seed 0:  14%|█▍        | 7/50 [27:48<2:51:15, 238.97s/it, best=55.05%, train_loss=0.6845, val_acc=55.05%, val_loss=0.6843]

seed 0:  14%|█▍        | 7/50 [31:50<2:51:15, 238.97s/it, best=55.09%, train_loss=0.6844, val_acc=55.09%, val_loss=0.6843]

seed 0:  16%|█▌        | 8/50 [31:50<2:48:03, 240.09s/it, best=55.09%, train_loss=0.6844, val_acc=55.09%, val_loss=0.6843]

seed 0:  16%|█▌        | 8/50 [35:52<2:48:03, 240.09s/it, best=55.09%, train_loss=0.6842, val_acc=55.03%, val_loss=0.6847]

seed 0:  18%|█▊        | 9/50 [35:52<2:44:28, 240.71s/it, best=55.09%, train_loss=0.6842, val_acc=55.03%, val_loss=0.6847]

seed 0:  18%|█▊        | 9/50 [39:55<2:44:28, 240.71s/it, best=55.09%, train_loss=0.6841, val_acc=55.05%, val_loss=0.6841]

seed 0:  20%|█▊       | 10/50 [39:55<2:40:59, 241.49s/it, best=55.09%, train_loss=0.6841, val_acc=55.05%, val_loss=0.6841]

seed 0:  20%|█▊       | 10/50 [43:58<2:40:59, 241.49s/it, best=55.10%, train_loss=0.6841, val_acc=55.10%, val_loss=0.6840]

seed 0:  22%|█▉       | 11/50 [43:58<2:37:09, 241.77s/it, best=55.10%, train_loss=0.6841, val_acc=55.10%, val_loss=0.6840]

seed 0:  22%|█▉       | 11/50 [48:00<2:37:09, 241.77s/it, best=55.10%, train_loss=0.6840, val_acc=55.04%, val_loss=0.6841]

seed 0:  24%|██▏      | 12/50 [48:00<2:33:15, 241.98s/it, best=55.10%, train_loss=0.6840, val_acc=55.04%, val_loss=0.6841]

seed 0:  24%|██▏      | 12/50 [52:05<2:33:15, 241.98s/it, best=55.13%, train_loss=0.6839, val_acc=55.13%, val_loss=0.6841]

seed 0:  26%|██▎      | 13/50 [52:05<2:29:40, 242.71s/it, best=55.13%, train_loss=0.6839, val_acc=55.13%, val_loss=0.6841]

seed 0:  26%|██▎      | 13/50 [56:08<2:29:40, 242.71s/it, best=55.13%, train_loss=0.6838, val_acc=55.12%, val_loss=0.6840]

seed 0:  28%|██▌      | 14/50 [56:08<2:25:49, 243.05s/it, best=55.13%, train_loss=0.6838, val_acc=55.12%, val_loss=0.6840]

seed 0:  28%|█▉     | 14/50 [1:00:13<2:25:49, 243.05s/it, best=55.13%, train_loss=0.6838, val_acc=55.08%, val_loss=0.6841]

seed 0:  30%|██     | 15/50 [1:00:13<2:22:05, 243.59s/it, best=55.13%, train_loss=0.6838, val_acc=55.08%, val_loss=0.6841]

seed 0:  30%|██     | 15/50 [1:04:19<2:22:05, 243.59s/it, best=55.14%, train_loss=0.6837, val_acc=55.14%, val_loss=0.6840]

seed 0:  32%|██▏    | 16/50 [1:04:19<2:18:23, 244.23s/it, best=55.14%, train_loss=0.6837, val_acc=55.14%, val_loss=0.6840]

seed 0:  32%|██▏    | 16/50 [1:08:22<2:18:23, 244.23s/it, best=55.14%, train_loss=0.6837, val_acc=55.12%, val_loss=0.6840]

seed 0:  34%|██▍    | 17/50 [1:08:22<2:14:10, 243.96s/it, best=55.14%, train_loss=0.6837, val_acc=55.12%, val_loss=0.6840]

seed 0:  34%|██▍    | 17/50 [1:12:28<2:14:10, 243.96s/it, best=55.18%, train_loss=0.6831, val_acc=55.18%, val_loss=0.6839]

seed 0:  36%|██▌    | 18/50 [1:12:28<2:10:19, 244.35s/it, best=55.18%, train_loss=0.6831, val_acc=55.18%, val_loss=0.6839]

seed 0:  36%|██▌    | 18/50 [1:16:32<2:10:19, 244.35s/it, best=55.19%, train_loss=0.6830, val_acc=55.19%, val_loss=0.6838]

seed 0:  38%|██▋    | 19/50 [1:16:32<2:06:19, 244.49s/it, best=55.19%, train_loss=0.6830, val_acc=55.19%, val_loss=0.6838]

seed 0:  38%|██▋    | 19/50 [1:20:34<2:06:19, 244.49s/it, best=55.19%, train_loss=0.6829, val_acc=55.16%, val_loss=0.6839]

seed 0:  40%|██▊    | 20/50 [1:20:34<2:01:44, 243.48s/it, best=55.19%, train_loss=0.6829, val_acc=55.16%, val_loss=0.6839]

seed 0:  40%|██▊    | 20/50 [1:24:35<2:01:44, 243.48s/it, best=55.19%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6839]

seed 0:  42%|██▉    | 21/50 [1:24:35<1:57:20, 242.78s/it, best=55.19%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6839]

seed 0:  42%|██▉    | 21/50 [1:28:36<1:57:20, 242.78s/it, best=55.19%, train_loss=0.6829, val_acc=55.18%, val_loss=0.6839]

seed 0:  44%|███    | 22/50 [1:28:36<1:53:06, 242.37s/it, best=55.19%, train_loss=0.6829, val_acc=55.18%, val_loss=0.6839]

seed 0:  44%|███    | 22/50 [1:32:37<1:53:06, 242.37s/it, best=55.19%, train_loss=0.6827, val_acc=55.17%, val_loss=0.6839]

seed 0:  46%|███▏   | 23/50 [1:32:37<1:48:49, 241.83s/it, best=55.19%, train_loss=0.6827, val_acc=55.17%, val_loss=0.6839]

seed 0:  46%|███▏   | 23/50 [1:36:40<1:48:49, 241.83s/it, best=55.19%, train_loss=0.6828, val_acc=55.17%, val_loss=0.6839]

seed 0:  46%|▍| 23/50 [1:36:40<1:48:49, 241.83s/it, early_stop=epoch 24, train_loss=0.6828, val_acc=55.17%, val_loss=0.683

ensemble runs:  10%|█████▌                                                  | 1/10 [1:36:48<14:31:15, 5808.34s/it, seed=0]

ensemble runs:  10%|█████▌                                                  | 1/10 [1:36:48<14:31:15, 5808.34s/it, seed=1]

seed 1:   0%|                                                                                      | 0/50 [00:00<?, ?it/s]

seed 1:   0%|                     | 0/50 [04:00<?, ?it/s, best=54.80%, train_loss=0.6992, val_acc=54.80%, val_loss=0.6853]

seed 1:   2%|▏         | 1/50 [04:00<3:16:21, 240.44s/it, best=54.80%, train_loss=0.6992, val_acc=54.80%, val_loss=0.6853]

seed 1:   2%|▏         | 1/50 [08:01<3:16:21, 240.44s/it, best=54.84%, train_loss=0.6901, val_acc=54.84%, val_loss=0.6850]

seed 1:   4%|▍         | 2/50 [08:01<3:12:26, 240.54s/it, best=54.84%, train_loss=0.6901, val_acc=54.84%, val_loss=0.6850]

seed 1:   4%|▍         | 2/50 [12:03<3:12:26, 240.54s/it, best=54.84%, train_loss=0.6869, val_acc=54.10%, val_loss=0.6866]

seed 1:   6%|▌         | 3/50 [12:03<3:09:10, 241.51s/it, best=54.84%, train_loss=0.6869, val_acc=54.10%, val_loss=0.6866]

seed 1:   6%|▌         | 3/50 [16:04<3:09:10, 241.51s/it, best=54.91%, train_loss=0.6854, val_acc=54.91%, val_loss=0.6846]

seed 1:   8%|▊         | 4/50 [16:04<3:04:57, 241.25s/it, best=54.91%, train_loss=0.6854, val_acc=54.91%, val_loss=0.6846]

seed 1:   8%|▊         | 4/50 [20:03<3:04:57, 241.25s/it, best=55.04%, train_loss=0.6849, val_acc=55.04%, val_loss=0.6844]

seed 1:  10%|█         | 5/50 [20:03<3:00:26, 240.59s/it, best=55.04%, train_loss=0.6849, val_acc=55.04%, val_loss=0.6844]

seed 1:  10%|█         | 5/50 [24:06<3:00:26, 240.59s/it, best=55.06%, train_loss=0.6847, val_acc=55.06%, val_loss=0.6842]

seed 1:  12%|█▏        | 6/50 [24:06<2:56:47, 241.09s/it, best=55.06%, train_loss=0.6847, val_acc=55.06%, val_loss=0.6842]

seed 1:  12%|█▏        | 6/50 [28:05<2:56:47, 241.09s/it, best=55.06%, train_loss=0.6845, val_acc=55.06%, val_loss=0.6842]

seed 1:  14%|█▍        | 7/50 [28:05<2:52:23, 240.55s/it, best=55.06%, train_loss=0.6845, val_acc=55.06%, val_loss=0.6842]

seed 1:  14%|█▍        | 7/50 [32:07<2:52:23, 240.55s/it, best=55.06%, train_loss=0.6844, val_acc=54.96%, val_loss=0.6845]

seed 1:  16%|█▌        | 8/50 [32:07<2:48:48, 241.15s/it, best=55.06%, train_loss=0.6844, val_acc=54.96%, val_loss=0.6845]

seed 1:  16%|█▌        | 8/50 [36:09<2:48:48, 241.15s/it, best=55.06%, train_loss=0.6843, val_acc=55.05%, val_loss=0.6842]

seed 1:  18%|█▊        | 9/50 [36:09<2:44:53, 241.30s/it, best=55.06%, train_loss=0.6843, val_acc=55.05%, val_loss=0.6842]

seed 1:  18%|█▊        | 9/50 [40:14<2:44:53, 241.30s/it, best=55.06%, train_loss=0.6842, val_acc=55.06%, val_loss=0.6842]

seed 1:  20%|█▊       | 10/50 [40:14<2:41:33, 242.33s/it, best=55.06%, train_loss=0.6842, val_acc=55.06%, val_loss=0.6842]

seed 1:  20%|█▊       | 10/50 [44:17<2:41:33, 242.33s/it, best=55.06%, train_loss=0.6841, val_acc=55.05%, val_loss=0.6843]

seed 1:  22%|█▉       | 11/50 [44:17<2:37:38, 242.52s/it, best=55.06%, train_loss=0.6841, val_acc=55.05%, val_loss=0.6843]

seed 1:  22%|█▉       | 11/50 [48:22<2:37:38, 242.52s/it, best=55.10%, train_loss=0.6840, val_acc=55.10%, val_loss=0.6841]

seed 1:  24%|██▏      | 12/50 [48:22<2:34:13, 243.52s/it, best=55.10%, train_loss=0.6840, val_acc=55.10%, val_loss=0.6841]

seed 1:  24%|██▏      | 12/50 [52:24<2:34:13, 243.52s/it, best=55.10%, train_loss=0.6840, val_acc=55.08%, val_loss=0.6841]

seed 1:  26%|██▎      | 13/50 [52:24<2:29:50, 242.99s/it, best=55.10%, train_loss=0.6840, val_acc=55.08%, val_loss=0.6841]

seed 1:  26%|██▎      | 13/50 [56:30<2:29:50, 242.99s/it, best=55.11%, train_loss=0.6839, val_acc=55.11%, val_loss=0.6841]

seed 1:  28%|██▌      | 14/50 [56:30<2:26:20, 243.89s/it, best=55.11%, train_loss=0.6839, val_acc=55.11%, val_loss=0.6841]

seed 1:  28%|█▉     | 14/50 [1:00:33<2:26:20, 243.89s/it, best=55.11%, train_loss=0.6838, val_acc=55.09%, val_loss=0.6841]

seed 1:  30%|██     | 15/50 [1:00:33<2:22:02, 243.50s/it, best=55.11%, train_loss=0.6838, val_acc=55.09%, val_loss=0.6841]

seed 1:  30%|██     | 15/50 [1:04:38<2:22:02, 243.50s/it, best=55.15%, train_loss=0.6833, val_acc=55.15%, val_loss=0.6839]

seed 1:  32%|██▏    | 16/50 [1:04:38<2:18:18, 244.08s/it, best=55.15%, train_loss=0.6833, val_acc=55.15%, val_loss=0.6839]

seed 1:  32%|██▏    | 16/50 [1:08:40<2:18:18, 244.08s/it, best=55.15%, train_loss=0.6832, val_acc=55.15%, val_loss=0.6839]

seed 1:  34%|██▍    | 17/50 [1:08:40<2:13:49, 243.33s/it, best=55.15%, train_loss=0.6832, val_acc=55.15%, val_loss=0.6839]

seed 1:  34%|██▍    | 17/50 [1:12:44<2:13:49, 243.33s/it, best=55.15%, train_loss=0.6831, val_acc=55.14%, val_loss=0.6839]

seed 1:  36%|██▌    | 18/50 [1:12:44<2:09:56, 243.63s/it, best=55.15%, train_loss=0.6831, val_acc=55.14%, val_loss=0.6839]

seed 1:  36%|██▌    | 18/50 [1:16:45<2:09:56, 243.63s/it, best=55.15%, train_loss=0.6831, val_acc=55.13%, val_loss=0.6839]

seed 1:  38%|██▋    | 19/50 [1:16:45<2:05:28, 242.86s/it, best=55.15%, train_loss=0.6831, val_acc=55.13%, val_loss=0.6839]

seed 1:  38%|██▋    | 19/50 [1:20:49<2:05:28, 242.86s/it, best=55.15%, train_loss=0.6830, val_acc=55.12%, val_loss=0.6839]

seed 1:  40%|██▊    | 20/50 [1:20:49<2:01:33, 243.11s/it, best=55.15%, train_loss=0.6830, val_acc=55.12%, val_loss=0.6839]

seed 1:  40%|██▊    | 20/50 [1:24:51<2:01:33, 243.11s/it, best=55.15%, train_loss=0.6830, val_acc=55.13%, val_loss=0.6839]

seed 1:  42%|██▉    | 21/50 [1:24:51<1:57:17, 242.67s/it, best=55.15%, train_loss=0.6830, val_acc=55.13%, val_loss=0.6839]

seed 1:  42%|██▉    | 21/50 [1:28:55<1:57:17, 242.67s/it, best=55.15%, train_loss=0.6830, val_acc=55.12%, val_loss=0.6839]

seed 1:  44%|███    | 22/50 [1:28:55<1:53:30, 243.23s/it, best=55.15%, train_loss=0.6830, val_acc=55.12%, val_loss=0.6839]

seed 1:  44%|███    | 22/50 [1:32:55<1:53:30, 243.23s/it, best=55.15%, train_loss=0.6829, val_acc=55.14%, val_loss=0.6839]

seed 1:  46%|███▏   | 23/50 [1:32:55<1:48:57, 242.11s/it, best=55.15%, train_loss=0.6829, val_acc=55.14%, val_loss=0.6839]

seed 1:  46%|███▏   | 23/50 [1:36:58<1:48:57, 242.11s/it, best=55.15%, train_loss=0.6829, val_acc=55.13%, val_loss=0.6839]

seed 1:  48%|███▎   | 24/50 [1:36:58<1:45:03, 242.45s/it, best=55.15%, train_loss=0.6829, val_acc=55.13%, val_loss=0.6839]

seed 1:  48%|███▎   | 24/50 [1:40:55<1:45:03, 242.45s/it, best=55.15%, train_loss=0.6829, val_acc=55.13%, val_loss=0.6839]

seed 1:  50%|███▌   | 25/50 [1:40:55<1:40:25, 241.02s/it, best=55.15%, train_loss=0.6829, val_acc=55.13%, val_loss=0.6839]

seed 1:  50%|███▌   | 25/50 [1:44:57<1:40:25, 241.02s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  52%|███▋   | 26/50 [1:44:57<1:36:27, 241.13s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  52%|███▋   | 26/50 [1:48:58<1:36:27, 241.13s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  54%|███▊   | 27/50 [1:48:58<1:32:27, 241.21s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  54%|███▊   | 27/50 [1:52:59<1:32:27, 241.21s/it, best=55.15%, train_loss=0.6829, val_acc=55.12%, val_loss=0.6839]

seed 1:  56%|███▉   | 28/50 [1:52:59<1:28:23, 241.08s/it, best=55.15%, train_loss=0.6829, val_acc=55.12%, val_loss=0.6839]

seed 1:  56%|███▉   | 28/50 [1:57:04<1:28:23, 241.08s/it, best=55.15%, train_loss=0.6829, val_acc=55.12%, val_loss=0.6839]

seed 1:  58%|████   | 29/50 [1:57:04<1:24:46, 242.21s/it, best=55.15%, train_loss=0.6829, val_acc=55.12%, val_loss=0.6839]

seed 1:  58%|████   | 29/50 [2:01:05<1:24:46, 242.21s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  60%|████▏  | 30/50 [2:01:05<1:20:36, 241.84s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  60%|████▏  | 30/50 [2:05:10<1:20:36, 241.84s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  62%|████▎  | 31/50 [2:05:10<1:16:51, 242.71s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  62%|████▎  | 31/50 [2:09:14<1:16:51, 242.71s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  64%|████▍  | 32/50 [2:09:14<1:12:55, 243.10s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  64%|████▍  | 32/50 [2:12:52<1:12:55, 243.10s/it, best=55.15%, train_loss=0.6828, val_acc=55.12%, val_loss=0.6839]

seed 1:  64%|▋| 32/50 [2:12:52<1:12:55, 243.10s/it, early_stop=epoch 33, train_loss=0.6828, val_acc=55.12%, val_loss=0.683

ensemble runs:  20%|███████████▏                                            | 2/10 [3:49:48<15:44:46, 7085.82s/it, seed=1]

ensemble runs:  20%|███████████▏                                            | 2/10 [3:49:48<15:44:46, 7085.82s/it, seed=2]

seed 2:   0%|                                                                                      | 0/50 [00:00<?, ?it/s]

seed 2:   0%|                     | 0/50 [03:38<?, ?it/s, best=54.34%, train_loss=0.6990, val_acc=54.34%, val_loss=0.6870]

seed 2:   2%|▏         | 1/50 [03:38<2:58:31, 218.61s/it, best=54.34%, train_loss=0.6990, val_acc=54.34%, val_loss=0.6870]

seed 2:   2%|▏         | 1/50 [07:17<2:58:31, 218.61s/it, best=54.34%, train_loss=0.6902, val_acc=54.14%, val_loss=0.6873]

seed 2:   4%|▍         | 2/50 [07:17<2:54:47, 218.50s/it, best=54.34%, train_loss=0.6902, val_acc=54.14%, val_loss=0.6873]

seed 2:   4%|▍         | 2/50 [10:55<2:54:47, 218.50s/it, best=54.80%, train_loss=0.6870, val_acc=54.80%, val_loss=0.6851]

seed 2:   6%|▌         | 3/50 [10:55<2:51:16, 218.65s/it, best=54.80%, train_loss=0.6870, val_acc=54.80%, val_loss=0.6851]

seed 2:   6%|▌         | 3/50 [14:33<2:51:16, 218.65s/it, best=54.90%, train_loss=0.6855, val_acc=54.90%, val_loss=0.6851]

seed 2:   8%|▊         | 4/50 [14:33<2:47:24, 218.36s/it, best=54.90%, train_loss=0.6855, val_acc=54.90%, val_loss=0.6851]

seed 2:   8%|▊         | 4/50 [18:10<2:47:24, 218.36s/it, best=54.92%, train_loss=0.6849, val_acc=54.92%, val_loss=0.6847]

seed 2:  10%|█         | 5/50 [18:10<2:43:14, 217.66s/it, best=54.92%, train_loss=0.6849, val_acc=54.92%, val_loss=0.6847]

seed 2:  10%|█         | 5/50 [21:46<2:43:14, 217.66s/it, best=55.02%, train_loss=0.6846, val_acc=55.02%, val_loss=0.6844]

seed 2:  12%|█▏        | 6/50 [21:46<2:39:15, 217.16s/it, best=55.02%, train_loss=0.6846, val_acc=55.02%, val_loss=0.6844]

seed 2:  12%|█▏        | 6/50 [25:22<2:39:15, 217.16s/it, best=55.02%, train_loss=0.6845, val_acc=54.99%, val_loss=0.6845]

seed 2:  14%|█▍        | 7/50 [25:22<2:35:24, 216.85s/it, best=55.02%, train_loss=0.6845, val_acc=54.99%, val_loss=0.6845]

seed 2:  14%|█▍        | 7/50 [28:58<2:35:24, 216.85s/it, best=55.02%, train_loss=0.6843, val_acc=55.01%, val_loss=0.6843]

seed 2:  16%|█▌        | 8/50 [28:58<2:31:34, 216.53s/it, best=55.02%, train_loss=0.6843, val_acc=55.01%, val_loss=0.6843]

seed 2:  16%|█▌        | 8/50 [32:34<2:31:34, 216.53s/it, best=55.02%, train_loss=0.6842, val_acc=55.01%, val_loss=0.6843]

seed 2:  18%|█▊        | 9/50 [32:34<2:27:55, 216.48s/it, best=55.02%, train_loss=0.6842, val_acc=55.01%, val_loss=0.6843]

seed 2:  18%|█▊        | 9/50 [36:13<2:27:55, 216.48s/it, best=55.04%, train_loss=0.6841, val_acc=55.04%, val_loss=0.6842]

seed 2:  20%|█▊       | 10/50 [36:13<2:24:42, 217.07s/it, best=55.04%, train_loss=0.6841, val_acc=55.04%, val_loss=0.6842]

seed 2:  20%|█▊       | 10/50 [39:52<2:24:42, 217.07s/it, best=55.04%, train_loss=0.6840, val_acc=55.00%, val_loss=0.6843]

seed 2:  22%|█▉       | 11/50 [39:52<2:21:28, 217.64s/it, best=55.04%, train_loss=0.6840, val_acc=55.00%, val_loss=0.6843]

seed 2:  22%|█▉       | 11/50 [43:30<2:21:28, 217.64s/it, best=55.09%, train_loss=0.6840, val_acc=55.09%, val_loss=0.6842]

seed 2:  24%|██▏      | 12/50 [43:30<2:17:53, 217.72s/it, best=55.09%, train_loss=0.6840, val_acc=55.09%, val_loss=0.6842]

seed 2:  24%|██▏      | 12/50 [47:08<2:17:53, 217.72s/it, best=55.09%, train_loss=0.6839, val_acc=55.07%, val_loss=0.6841]

seed 2:  26%|██▎      | 13/50 [47:08<2:14:25, 217.99s/it, best=55.09%, train_loss=0.6839, val_acc=55.07%, val_loss=0.6841]

seed 2:  26%|██▎      | 13/50 [50:40<2:14:25, 217.99s/it, best=55.09%, train_loss=0.6838, val_acc=55.03%, val_loss=0.6842]

seed 2:  28%|██▌      | 14/50 [50:40<2:09:38, 216.07s/it, best=55.09%, train_loss=0.6838, val_acc=55.03%, val_loss=0.6842]

seed 2:  28%|██▌      | 14/50 [54:13<2:09:38, 216.07s/it, best=55.09%, train_loss=0.6837, val_acc=55.02%, val_loss=0.6842]

seed 2:  30%|██▋      | 15/50 [54:13<2:05:34, 215.28s/it, best=55.09%, train_loss=0.6837, val_acc=55.02%, val_loss=0.6842]

seed 2:  30%|██▋      | 15/50 [57:50<2:05:34, 215.28s/it, best=55.09%, train_loss=0.6837, val_acc=55.02%, val_loss=0.6844]

seed 2:  32%|██▉      | 16/50 [57:50<2:02:14, 215.71s/it, best=55.09%, train_loss=0.6837, val_acc=55.02%, val_loss=0.6844]

seed 2:  32%|██▏    | 16/50 [1:01:24<2:02:14, 215.71s/it, best=55.09%, train_loss=0.6836, val_acc=55.04%, val_loss=0.6842]

seed 2:  34%|██▍    | 17/50 [1:01:24<1:58:17, 215.07s/it, best=55.09%, train_loss=0.6836, val_acc=55.04%, val_loss=0.6842]

seed 2:  34%|██▍    | 17/50 [1:04:59<1:58:17, 215.07s/it, best=55.09%, train_loss=0.6835, val_acc=55.04%, val_loss=0.6841]

seed 2:  36%|██▌    | 18/50 [1:04:59<1:54:48, 215.26s/it, best=55.09%, train_loss=0.6835, val_acc=55.04%, val_loss=0.6841]

seed 2:  36%|██▌    | 18/50 [1:08:34<1:54:48, 215.26s/it, best=55.09%, train_loss=0.6830, val_acc=55.06%, val_loss=0.6840]

seed 2:  38%|██▋    | 19/50 [1:08:34<1:51:07, 215.08s/it, best=55.09%, train_loss=0.6830, val_acc=55.06%, val_loss=0.6840]

seed 2:  38%|██▋    | 19/50 [1:12:04<1:51:07, 215.08s/it, best=55.09%, train_loss=0.6828, val_acc=55.06%, val_loss=0.6840]

seed 2:  40%|██▊    | 20/50 [1:12:04<1:46:49, 213.64s/it, best=55.09%, train_loss=0.6828, val_acc=55.06%, val_loss=0.6840]

seed 2:  40%|██▊    | 20/50 [1:15:35<1:46:49, 213.64s/it, best=55.09%, train_loss=0.6827, val_acc=55.06%, val_loss=0.6840]

seed 2:  42%|██▉    | 21/50 [1:15:35<1:42:48, 212.71s/it, best=55.09%, train_loss=0.6827, val_acc=55.06%, val_loss=0.6840]

seed 2:  42%|██▉    | 21/50 [1:19:07<1:42:48, 212.71s/it, best=55.09%, train_loss=0.6827, val_acc=55.05%, val_loss=0.6840]

seed 2:  44%|███    | 22/50 [1:19:07<1:39:12, 212.60s/it, best=55.09%, train_loss=0.6827, val_acc=55.05%, val_loss=0.6840]

seed 2:  44%|███    | 22/50 [1:22:40<1:39:12, 212.60s/it, best=55.09%, train_loss=0.6827, val_acc=55.07%, val_loss=0.6840]

seed 2:  46%|███▏   | 23/50 [1:22:40<1:35:39, 212.57s/it, best=55.09%, train_loss=0.6827, val_acc=55.07%, val_loss=0.6840]

seed 2:  46%|███▏   | 23/50 [1:26:13<1:35:39, 212.57s/it, best=55.09%, train_loss=0.6827, val_acc=55.07%, val_loss=0.6840]

seed 2:  48%|███▎   | 24/50 [1:26:13<1:32:16, 212.95s/it, best=55.09%, train_loss=0.6827, val_acc=55.07%, val_loss=0.6840]

seed 2:  48%|███▎   | 24/50 [1:29:48<1:32:16, 212.95s/it, best=55.09%, train_loss=0.6825, val_acc=55.06%, val_loss=0.6840]

seed 2:  50%|███▌   | 25/50 [1:29:48<1:28:58, 213.53s/it, best=55.09%, train_loss=0.6825, val_acc=55.06%, val_loss=0.6840]

seed 2:  50%|███▌   | 25/50 [1:33:22<1:28:58, 213.53s/it, best=55.09%, train_loss=0.6825, val_acc=55.06%, val_loss=0.6840]

seed 2:  52%|███▋   | 26/50 [1:33:22<1:25:25, 213.55s/it, best=55.09%, train_loss=0.6825, val_acc=55.06%, val_loss=0.6840]

seed 2:  52%|███▋   | 26/50 [1:36:54<1:25:25, 213.55s/it, best=55.09%, train_loss=0.6825, val_acc=55.06%, val_loss=0.6840]

seed 2:  54%|███▊   | 27/50 [1:36:54<1:21:43, 213.19s/it, best=55.09%, train_loss=0.6825, val_acc=55.06%, val_loss=0.6840]

seed 2:  54%|███▊   | 27/50 [1:40:26<1:21:43, 213.19s/it, best=55.09%, train_loss=0.6825, val_acc=55.05%, val_loss=0.6840]

seed 2:  56%|███▉   | 28/50 [1:40:26<1:18:03, 212.87s/it, best=55.09%, train_loss=0.6825, val_acc=55.05%, val_loss=0.6840]

seed 2:  56%|███▉   | 28/50 [1:44:03<1:18:03, 212.87s/it, best=55.09%, train_loss=0.6825, val_acc=55.06%, val_loss=0.6840]

seed 2:  56%|▌| 28/50 [1:44:03<1:18:03, 212.87s/it, early_stop=epoch 29, train_loss=0.6825, val_acc=55.06%, val_loss=0.684

ensemble runs:  30%|████████████████▊                                       | 3/10 [5:33:57<13:02:07, 6703.87s/it, seed=2]

ensemble runs:  30%|████████████████▊                                       | 3/10 [5:33:57<13:02:07, 6703.87s/it, seed=3]

seed 3:   0%|                                                                                      | 0/50 [00:00<?, ?it/s]

seed 3:   0%|                     | 0/50 [03:37<?, ?it/s, best=54.82%, train_loss=0.6993, val_acc=54.82%, val_loss=0.6854]

seed 3:   2%|▏         | 1/50 [03:37<2:57:14, 217.04s/it, best=54.82%, train_loss=0.6993, val_acc=54.82%, val_loss=0.6854]

seed 3:   2%|▏         | 1/50 [07:11<2:57:14, 217.04s/it, best=54.82%, train_loss=0.6900, val_acc=53.50%, val_loss=0.6889]

seed 3:   4%|▍         | 2/50 [07:11<2:52:31, 215.66s/it, best=54.82%, train_loss=0.6900, val_acc=53.50%, val_loss=0.6889]

seed 3:   4%|▍         | 2/50 [10:46<2:52:31, 215.66s/it, best=54.88%, train_loss=0.6871, val_acc=54.88%, val_loss=0.6850]

seed 3:   6%|▌         | 3/50 [10:46<2:48:39, 215.31s/it, best=54.88%, train_loss=0.6871, val_acc=54.88%, val_loss=0.6850]

seed 3:   6%|▌         | 3/50 [14:22<2:48:39, 215.31s/it, best=54.98%, train_loss=0.6854, val_acc=54.98%, val_loss=0.6846]

seed 3:   8%|▊         | 4/50 [14:22<2:45:17, 215.60s/it, best=54.98%, train_loss=0.6854, val_acc=54.98%, val_loss=0.6846]

seed 3:   8%|▊         | 4/50 [17:58<2:45:17, 215.60s/it, best=55.06%, train_loss=0.6849, val_acc=55.06%, val_loss=0.6845]

seed 3:  10%|█         | 5/50 [17:58<2:41:39, 215.54s/it, best=55.06%, train_loss=0.6849, val_acc=55.06%, val_loss=0.6845]

seed 3:  10%|█         | 5/50 [21:34<2:41:39, 215.54s/it, best=55.06%, train_loss=0.6846, val_acc=54.98%, val_loss=0.6845]

seed 3:  12%|█▏        | 6/50 [21:34<2:38:13, 215.77s/it, best=55.06%, train_loss=0.6846, val_acc=54.98%, val_loss=0.6845]

seed 3:  12%|█▏        | 6/50 [25:10<2:38:13, 215.77s/it, best=55.10%, train_loss=0.6845, val_acc=55.10%, val_loss=0.6843]

seed 3:  14%|█▍        | 7/50 [25:10<2:34:42, 215.87s/it, best=55.10%, train_loss=0.6845, val_acc=55.10%, val_loss=0.6843]

seed 3:  14%|█▍        | 7/50 [28:46<2:34:42, 215.87s/it, best=55.10%, train_loss=0.6843, val_acc=55.03%, val_loss=0.6843]

seed 3:  16%|█▌        | 8/50 [28:46<2:31:09, 215.95s/it, best=55.10%, train_loss=0.6843, val_acc=55.03%, val_loss=0.6843]

seed 3:  16%|█▌        | 8/50 [32:20<2:31:09, 215.95s/it, best=55.10%, train_loss=0.6843, val_acc=55.06%, val_loss=0.6844]

seed 3:  18%|█▊        | 9/50 [32:20<2:27:08, 215.34s/it, best=55.10%, train_loss=0.6843, val_acc=55.06%, val_loss=0.6844]

seed 3:  18%|█▊        | 9/50 [35:53<2:27:08, 215.34s/it, best=55.10%, train_loss=0.6842, val_acc=55.10%, val_loss=0.6844]

seed 3:  20%|█▊       | 10/50 [35:53<2:23:08, 214.71s/it, best=55.10%, train_loss=0.6842, val_acc=55.10%, val_loss=0.6844]

seed 3:  20%|█▊       | 10/50 [39:25<2:23:08, 214.71s/it, best=55.10%, train_loss=0.6841, val_acc=55.09%, val_loss=0.6841]

seed 3:  22%|█▉       | 11/50 [39:25<2:18:54, 213.71s/it, best=55.10%, train_loss=0.6841, val_acc=55.09%, val_loss=0.6841]

seed 3:  22%|█▉       | 11/50 [42:56<2:18:54, 213.71s/it, best=55.14%, train_loss=0.6841, val_acc=55.14%, val_loss=0.6840]

seed 3:  24%|██▏      | 12/50 [42:56<2:14:56, 213.08s/it, best=55.14%, train_loss=0.6841, val_acc=55.14%, val_loss=0.6840]

seed 3:  24%|██▏      | 12/50 [46:27<2:14:56, 213.08s/it, best=55.14%, train_loss=0.6840, val_acc=55.14%, val_loss=0.6840]

seed 3:  26%|██▎      | 13/50 [46:27<2:10:53, 212.25s/it, best=55.14%, train_loss=0.6840, val_acc=55.14%, val_loss=0.6840]

seed 3:  26%|██▎      | 13/50 [49:59<2:10:53, 212.25s/it, best=55.14%, train_loss=0.6839, val_acc=55.03%, val_loss=0.6843]

seed 3:  28%|██▌      | 14/50 [49:59<2:07:23, 212.32s/it, best=55.14%, train_loss=0.6839, val_acc=55.03%, val_loss=0.6843]

seed 3:  28%|██▌      | 14/50 [53:33<2:07:23, 212.32s/it, best=55.16%, train_loss=0.6838, val_acc=55.16%, val_loss=0.6841]

seed 3:  30%|██▋      | 15/50 [53:33<2:04:05, 212.74s/it, best=55.16%, train_loss=0.6838, val_acc=55.16%, val_loss=0.6841]

seed 3:  30%|██▋      | 15/50 [57:07<2:04:05, 212.74s/it, best=55.16%, train_loss=0.6838, val_acc=55.12%, val_loss=0.6840]

seed 3:  32%|██▉      | 16/50 [57:07<2:00:41, 213.00s/it, best=55.16%, train_loss=0.6838, val_acc=55.12%, val_loss=0.6840]

seed 3:  32%|██▏    | 16/50 [1:00:41<2:00:41, 213.00s/it, best=55.16%, train_loss=0.6837, val_acc=55.06%, val_loss=0.6843]

seed 3:  32%|▎| 16/50 [1:00:41<2:00:41, 213.00s/it, early_stop=epoch 17, train_loss=0.6837, val_acc=55.06%, val_loss=0.684

ensemble runs:  40%|██████████████████████▊                                  | 4/10 [6:34:44<9:09:42, 5497.06s/it, seed=3]

ensemble runs:  40%|██████████████████████▊                                  | 4/10 [6:34:44<9:09:42, 5497.06s/it, seed=4]

seed 4:   0%|                                                                                      | 0/50 [00:00<?, ?it/s]

seed 4:   0%|                     | 0/50 [03:33<?, ?it/s, best=52.37%, train_loss=0.6989, val_acc=52.37%, val_loss=0.6953]

seed 4:   2%|▏         | 1/50 [03:33<2:54:26, 213.59s/it, best=52.37%, train_loss=0.6989, val_acc=52.37%, val_loss=0.6953]

seed 4:   2%|▏         | 1/50 [07:06<2:54:26, 213.59s/it, best=54.87%, train_loss=0.6902, val_acc=54.87%, val_loss=0.6851]

seed 4:   4%|▍         | 2/50 [07:06<2:50:32, 213.18s/it, best=54.87%, train_loss=0.6902, val_acc=54.87%, val_loss=0.6851]

seed 4:   4%|▍         | 2/50 [10:38<2:50:32, 213.18s/it, best=54.87%, train_loss=0.6870, val_acc=54.75%, val_loss=0.6852]

seed 4:   6%|▌         | 3/50 [10:38<2:46:41, 212.81s/it, best=54.87%, train_loss=0.6870, val_acc=54.75%, val_loss=0.6852]

seed 4:   6%|▌         | 3/50 [14:11<2:46:41, 212.81s/it, best=54.93%, train_loss=0.6855, val_acc=54.93%, val_loss=0.6844]

seed 4:   8%|▊         | 4/50 [14:11<2:43:01, 212.64s/it, best=54.93%, train_loss=0.6855, val_acc=54.93%, val_loss=0.6844]

seed 4:   8%|▊         | 4/50 [17:35<2:43:01, 212.64s/it, best=54.99%, train_loss=0.6849, val_acc=54.99%, val_loss=0.6842]

seed 4:  10%|█         | 5/50 [17:35<2:37:14, 209.66s/it, best=54.99%, train_loss=0.6849, val_acc=54.99%, val_loss=0.6842]

seed 4:  10%|█         | 5/50 [21:12<2:37:14, 209.66s/it, best=54.99%, train_loss=0.6846, val_acc=54.96%, val_loss=0.6844]

seed 4:  12%|█▏        | 6/50 [21:12<2:35:28, 212.02s/it, best=54.99%, train_loss=0.6846, val_acc=54.96%, val_loss=0.6844]

seed 4:  12%|█▏        | 6/50 [24:51<2:35:28, 212.02s/it, best=55.00%, train_loss=0.6845, val_acc=55.00%, val_loss=0.6842]

seed 4:  14%|█▍        | 7/50 [24:51<2:33:32, 214.25s/it, best=55.00%, train_loss=0.6845, val_acc=55.00%, val_loss=0.6842]

seed 4:  14%|█▍        | 7/50 [28:30<2:33:32, 214.25s/it, best=55.04%, train_loss=0.6844, val_acc=55.04%, val_loss=0.6841]

seed 4:  16%|█▌        | 8/50 [28:30<2:31:04, 215.83s/it, best=55.04%, train_loss=0.6844, val_acc=55.04%, val_loss=0.6841]

seed 4:  16%|█▌        | 8/50 [32:09<2:31:04, 215.83s/it, best=55.05%, train_loss=0.6843, val_acc=55.05%, val_loss=0.6841]

seed 4:  18%|█▊        | 9/50 [32:09<2:28:16, 217.00s/it, best=55.05%, train_loss=0.6843, val_acc=55.05%, val_loss=0.6841]

seed 4:  18%|█▊        | 9/50 [35:47<2:28:16, 217.00s/it, best=55.05%, train_loss=0.6842, val_acc=55.04%, val_loss=0.6840]

seed 4:  20%|█▊       | 10/50 [35:47<2:24:47, 217.19s/it, best=55.05%, train_loss=0.6842, val_acc=55.04%, val_loss=0.6840]

seed 4:  20%|█▊       | 10/50 [39:26<2:24:47, 217.19s/it, best=55.05%, train_loss=0.6841, val_acc=55.04%, val_loss=0.6841]

seed 4:  22%|█▉       | 11/50 [39:26<2:21:29, 217.68s/it, best=55.05%, train_loss=0.6841, val_acc=55.04%, val_loss=0.6841]

seed 4:  22%|█▉       | 11/50 [43:02<2:21:29, 217.68s/it, best=55.06%, train_loss=0.6841, val_acc=55.06%, val_loss=0.6841]

seed 4:  24%|██▏      | 12/50 [43:02<2:17:35, 217.24s/it, best=55.06%, train_loss=0.6841, val_acc=55.06%, val_loss=0.6841]

seed 4:  24%|██▏      | 12/50 [46:39<2:17:35, 217.24s/it, best=55.09%, train_loss=0.6840, val_acc=55.09%, val_loss=0.6839]

seed 4:  26%|██▎      | 13/50 [46:39<2:13:51, 217.06s/it, best=55.09%, train_loss=0.6840, val_acc=55.09%, val_loss=0.6839]

seed 4:  26%|██▎      | 13/50 [50:15<2:13:51, 217.06s/it, best=55.09%, train_loss=0.6839, val_acc=55.08%, val_loss=0.6839]

seed 4:  28%|██▌      | 14/50 [50:15<2:10:07, 216.86s/it, best=55.09%, train_loss=0.6839, val_acc=55.08%, val_loss=0.6839]

seed 4:  28%|██▌      | 14/50 [53:52<2:10:07, 216.86s/it, best=55.09%, train_loss=0.6839, val_acc=55.08%, val_loss=0.6839]

seed 4:  30%|██▋      | 15/50 [53:52<2:06:26, 216.77s/it, best=55.09%, train_loss=0.6839, val_acc=55.08%, val_loss=0.6839]

seed 4:  30%|██▋      | 15/50 [57:27<2:06:26, 216.77s/it, best=55.09%, train_loss=0.6838, val_acc=55.09%, val_loss=0.6839]

seed 4:  32%|██▉      | 16/50 [57:27<2:02:39, 216.45s/it, best=55.09%, train_loss=0.6838, val_acc=55.09%, val_loss=0.6839]

seed 4:  32%|██▏    | 16/50 [1:01:05<2:02:39, 216.45s/it, best=55.11%, train_loss=0.6838, val_acc=55.11%, val_loss=0.6839]

seed 4:  34%|██▍    | 17/50 [1:01:05<1:59:10, 216.69s/it, best=55.11%, train_loss=0.6838, val_acc=55.11%, val_loss=0.6839]

seed 4:  34%|██▍    | 17/50 [1:04:41<1:59:10, 216.69s/it, best=55.11%, train_loss=0.6837, val_acc=55.07%, val_loss=0.6840]

seed 4:  36%|██▌    | 18/50 [1:04:41<1:55:33, 216.67s/it, best=55.11%, train_loss=0.6837, val_acc=55.07%, val_loss=0.6840]

seed 4:  36%|██▌    | 18/50 [1:08:14<1:55:33, 216.67s/it, best=55.11%, train_loss=0.6836, val_acc=54.96%, val_loss=0.6842]

seed 4:  38%|██▋    | 19/50 [1:08:14<1:51:25, 215.65s/it, best=55.11%, train_loss=0.6836, val_acc=54.96%, val_loss=0.6842]

seed 4:  38%|██▋    | 19/50 [1:11:49<1:51:25, 215.65s/it, best=55.11%, train_loss=0.6831, val_acc=55.09%, val_loss=0.6838]

seed 4:  40%|██▊    | 20/50 [1:11:49<1:47:38, 215.28s/it, best=55.11%, train_loss=0.6831, val_acc=55.09%, val_loss=0.6838]

seed 4:  40%|██▊    | 20/50 [1:15:23<1:47:38, 215.28s/it, best=55.13%, train_loss=0.6830, val_acc=55.13%, val_loss=0.6838]

seed 4:  42%|██▉    | 21/50 [1:15:23<1:43:57, 215.09s/it, best=55.13%, train_loss=0.6830, val_acc=55.13%, val_loss=0.6838]

seed 4:  42%|██▉    | 21/50 [1:18:59<1:43:57, 215.09s/it, best=55.13%, train_loss=0.6829, val_acc=55.12%, val_loss=0.6838]

seed 4:  44%|███    | 22/50 [1:18:59<1:40:24, 215.14s/it, best=55.13%, train_loss=0.6829, val_acc=55.12%, val_loss=0.6838]

seed 4:  44%|███    | 22/50 [1:22:35<1:40:24, 215.14s/it, best=55.13%, train_loss=0.6828, val_acc=55.11%, val_loss=0.6838]

seed 4:  46%|███▏   | 23/50 [1:22:35<1:36:59, 215.52s/it, best=55.13%, train_loss=0.6828, val_acc=55.11%, val_loss=0.6838]

seed 4:  46%|███▏   | 23/50 [1:26:12<1:36:59, 215.52s/it, best=55.13%, train_loss=0.6828, val_acc=55.11%, val_loss=0.6838]

seed 4:  48%|███▎   | 24/50 [1:26:12<1:33:34, 215.93s/it, best=55.13%, train_loss=0.6828, val_acc=55.11%, val_loss=0.6838]

seed 4:  48%|███▎   | 24/50 [1:29:50<1:33:34, 215.93s/it, best=55.13%, train_loss=0.6828, val_acc=55.11%, val_loss=0.6838]

seed 4:  50%|███▌   | 25/50 [1:29:50<1:30:11, 216.46s/it, best=55.13%, train_loss=0.6828, val_acc=55.11%, val_loss=0.6838]

seed 4:  50%|███▌   | 25/50 [1:33:24<1:30:11, 216.46s/it, best=55.13%, train_loss=0.6828, val_acc=55.13%, val_loss=0.6838]

seed 4:  52%|███▋   | 26/50 [1:33:24<1:26:17, 215.74s/it, best=55.13%, train_loss=0.6828, val_acc=55.13%, val_loss=0.6838]

seed 4:  52%|███▋   | 26/50 [1:36:57<1:26:17, 215.74s/it, best=55.13%, train_loss=0.6827, val_acc=55.11%, val_loss=0.6838]

seed 4:  54%|███▊   | 27/50 [1:36:57<1:22:24, 214.97s/it, best=55.13%, train_loss=0.6827, val_acc=55.11%, val_loss=0.6838]

seed 4:  54%|███▊   | 27/50 [1:40:33<1:22:24, 214.97s/it, best=55.13%, train_loss=0.6827, val_acc=55.12%, val_loss=0.6838]

seed 4:  56%|███▉   | 28/50 [1:40:33<1:18:56, 215.31s/it, best=55.13%, train_loss=0.6827, val_acc=55.12%, val_loss=0.6838]

seed 4:  56%|███▉   | 28/50 [1:44:06<1:18:56, 215.31s/it, best=55.13%, train_loss=0.6827, val_acc=55.11%, val_loss=0.6838]

seed 4:  56%|▌| 28/50 [1:44:06<1:18:56, 215.31s/it, early_stop=epoch 29, train_loss=0.6827, val_acc=55.11%, val_loss=0.683

ensemble runs:  50%|████████████████████████████▌                            | 5/10 [8:18:56<8:00:46, 5769.33s/it, seed=4]

ensemble runs:  50%|████████████████████████████▌                            | 5/10 [8:18:56<8:00:46, 5769.33s/it, seed=5]

seed 5:   0%|                                                                                      | 0/50 [00:00<?, ?it/s]

seed 5:   0%|                     | 0/50 [03:32<?, ?it/s, best=53.78%, train_loss=0.7000, val_acc=53.78%, val_loss=0.6887]

seed 5:   2%|▏         | 1/50 [03:32<2:53:37, 212.60s/it, best=53.78%, train_loss=0.7000, val_acc=53.78%, val_loss=0.6887]

seed 5:   2%|▏         | 1/50 [07:10<2:53:37, 212.60s/it, best=53.78%, train_loss=0.6904, val_acc=53.68%, val_loss=0.6879]

seed 5:   4%|▍         | 2/50 [07:10<2:52:32, 215.68s/it, best=53.78%, train_loss=0.6904, val_acc=53.68%, val_loss=0.6879]

seed 5:   4%|▍         | 2/50 [10:44<2:52:32, 215.68s/it, best=54.86%, train_loss=0.6872, val_acc=54.86%, val_loss=0.6849]

seed 5:   6%|▌         | 3/50 [10:44<2:48:29, 215.09s/it, best=54.86%, train_loss=0.6872, val_acc=54.86%, val_loss=0.6849]

seed 5:   6%|▌         | 3/50 [14:22<2:48:29, 215.09s/it, best=55.00%, train_loss=0.6856, val_acc=55.00%, val_loss=0.6844]

seed 5:   8%|▊         | 4/50 [14:22<2:45:45, 216.21s/it, best=55.00%, train_loss=0.6856, val_acc=55.00%, val_loss=0.6844]

seed 5:   8%|▊         | 4/50 [17:57<2:45:45, 216.21s/it, best=55.04%, train_loss=0.6850, val_acc=55.04%, val_loss=0.6843]

seed 5:  10%|█         | 5/50 [17:57<2:41:42, 215.62s/it, best=55.04%, train_loss=0.6850, val_acc=55.04%, val_loss=0.6843]

seed 5:  10%|█         | 5/50 [21:35<2:41:42, 215.62s/it, best=55.04%, train_loss=0.6848, val_acc=54.75%, val_loss=0.6851]

seed 5:  12%|█▏        | 6/50 [21:35<2:38:50, 216.60s/it, best=55.04%, train_loss=0.6848, val_acc=54.75%, val_loss=0.6851]

seed 5:  12%|█▏        | 6/50 [25:10<2:38:50, 216.60s/it, best=55.04%, train_loss=0.6845, val_acc=54.98%, val_loss=0.6845]

seed 5:  14%|█▍        | 7/50 [25:10<2:34:50, 216.06s/it, best=55.04%, train_loss=0.6845, val_acc=54.98%, val_loss=0.6845]

seed 5:  14%|█▍        | 7/50 [28:49<2:34:50, 216.06s/it, best=55.04%, train_loss=0.6844, val_acc=55.03%, val_loss=0.6843]

seed 5:  16%|█▌        | 8/50 [28:49<2:31:54, 217.02s/it, best=55.04%, train_loss=0.6844, val_acc=55.03%, val_loss=0.6843]

seed 5:  16%|█▌        | 8/50 [32:23<2:31:54, 217.02s/it, best=55.07%, train_loss=0.6843, val_acc=55.07%, val_loss=0.6842]

seed 5:  18%|█▊        | 9/50 [32:23<2:27:33, 215.94s/it, best=55.07%, train_loss=0.6843, val_acc=55.07%, val_loss=0.6842]

seed 5:  18%|█▊        | 9/50 [36:00<2:27:33, 215.94s/it, best=55.08%, train_loss=0.6841, val_acc=55.08%, val_loss=0.6840]

seed 5:  20%|█▊       | 10/50 [36:00<2:24:14, 216.37s/it, best=55.08%, train_loss=0.6841, val_acc=55.08%, val_loss=0.6840]

seed 5:  20%|█▊       | 10/50 [39:35<2:24:14, 216.37s/it, best=55.15%, train_loss=0.6840, val_acc=55.15%, val_loss=0.6839]

seed 5:  22%|█▉       | 11/50 [39:35<2:20:24, 216.01s/it, best=55.15%, train_loss=0.6840, val_acc=55.15%, val_loss=0.6839]

seed 5:  22%|█▉       | 11/50 [43:10<2:20:24, 216.01s/it, best=55.15%, train_loss=0.6840, val_acc=55.00%, val_loss=0.6841]

seed 5:  24%|██▏      | 12/50 [43:10<2:16:32, 215.59s/it, best=55.15%, train_loss=0.6840, val_acc=55.00%, val_loss=0.6841]

seed 5:  24%|██▏      | 12/50 [46:42<2:16:32, 215.59s/it, best=55.15%, train_loss=0.6839, val_acc=55.11%, val_loss=0.6840]

seed 5:  26%|██▎      | 13/50 [46:42<2:12:17, 214.52s/it, best=55.15%, train_loss=0.6839, val_acc=55.11%, val_loss=0.6840]

seed 5:  26%|██▎      | 13/50 [50:16<2:12:17, 214.52s/it, best=55.15%, train_loss=0.6838, val_acc=55.12%, val_loss=0.6840]

seed 5:  28%|██▌      | 14/50 [50:16<2:08:34, 214.30s/it, best=55.15%, train_loss=0.6838, val_acc=55.12%, val_loss=0.6840]

seed 5:  28%|██▌      | 14/50 [53:49<2:08:34, 214.30s/it, best=55.15%, train_loss=0.6838, val_acc=55.13%, val_loss=0.6840]

seed 5:  30%|██▋      | 15/50 [53:49<2:04:51, 214.05s/it, best=55.15%, train_loss=0.6838, val_acc=55.13%, val_loss=0.6840]

seed 5:  30%|██▋      | 15/50 [57:21<2:04:51, 214.05s/it, best=55.15%, train_loss=0.6837, val_acc=55.15%, val_loss=0.6841]

seed 5:  30%|▎| 15/50 [57:21<2:04:51, 214.05s/it, early_stop=epoch 16, train_loss=0.6837, val_acc=55.15%, val_loss=0.6841]

ensemble runs:  60%|██████████████████████████████████▏                      | 6/10 [9:16:23<5:31:58, 4979.71s/it, seed=5]

ensemble runs:  60%|██████████████████████████████████▏                      | 6/10 [9:16:23<5:31:58, 4979.71s/it, seed=6]

seed 6:   0%|                                                                                      | 0/50 [00:00<?, ?it/s]

seed 6:   0%|                     | 0/50 [03:36<?, ?it/s, best=53.85%, train_loss=0.6994, val_acc=53.85%, val_loss=0.6899]

seed 6:   2%|▏         | 1/50 [03:36<2:57:07, 216.89s/it, best=53.85%, train_loss=0.6994, val_acc=53.85%, val_loss=0.6899]

seed 6:   2%|▏         | 1/50 [07:08<2:57:07, 216.89s/it, best=54.46%, train_loss=0.6903, val_acc=54.46%, val_loss=0.6870]

seed 6:   4%|▍         | 2/50 [07:08<2:51:14, 214.05s/it, best=54.46%, train_loss=0.6903, val_acc=54.46%, val_loss=0.6870]

seed 6:   4%|▍         | 2/50 [10:47<2:51:14, 214.05s/it, best=54.46%, train_loss=0.6871, val_acc=54.46%, val_loss=0.6866]

seed 6:   6%|▌         | 3/50 [10:47<2:49:16, 216.10s/it, best=54.46%, train_loss=0.6871, val_acc=54.46%, val_loss=0.6866]

seed 6:   6%|▌         | 3/50 [14:25<2:49:16, 216.10s/it, best=55.00%, train_loss=0.6855, val_acc=55.00%, val_loss=0.6847]

seed 6:   8%|▊         | 4/50 [14:25<2:46:18, 216.93s/it, best=55.00%, train_loss=0.6855, val_acc=55.00%, val_loss=0.6847]

seed 6:   8%|▊         | 4/50 [17:57<2:46:18, 216.93s/it, best=55.10%, train_loss=0.6850, val_acc=55.10%, val_loss=0.6843]

seed 6:  10%|█         | 5/50 [17:57<2:41:18, 215.08s/it, best=55.10%, train_loss=0.6850, val_acc=55.10%, val_loss=0.6843]

seed 6:  10%|█         | 5/50 [21:32<2:41:18, 215.08s/it, best=55.10%, train_loss=0.6847, val_acc=55.08%, val_loss=0.6842]

seed 6:  12%|█▏        | 6/50 [21:32<2:37:48, 215.20s/it, best=55.10%, train_loss=0.6847, val_acc=55.08%, val_loss=0.6842]

seed 6:  12%|█▏        | 6/50 [24:57<2:37:48, 215.20s/it, best=55.11%, train_loss=0.6846, val_acc=55.11%, val_loss=0.6842]

seed 6:  14%|█▍        | 7/50 [24:57<2:31:40, 211.64s/it, best=55.11%, train_loss=0.6846, val_acc=55.11%, val_loss=0.6842]

seed 6:  14%|█▍        | 7/50 [27:47<2:31:40, 211.64s/it, best=55.11%, train_loss=0.6844, val_acc=55.10%, val_loss=0.6842]

seed 6:  16%|█▌        | 8/50 [27:47<2:18:53, 198.42s/it, best=55.11%, train_loss=0.6844, val_acc=55.10%, val_loss=0.6842]

seed 6:  16%|█▌        | 8/50 [30:39<2:18:53, 198.42s/it, best=55.11%, train_loss=0.6843, val_acc=55.09%, val_loss=0.6842]

seed 6:  18%|█▊        | 9/50 [30:39<2:09:52, 190.06s/it, best=55.11%, train_loss=0.6843, val_acc=55.09%, val_loss=0.6842]

seed 6:  18%|█▊        | 9/50 [33:32<2:09:52, 190.06s/it, best=55.16%, train_loss=0.6842, val_acc=55.16%, val_loss=0.6840]

seed 6:  20%|█▊       | 10/50 [33:32<2:03:17, 184.94s/it, best=55.16%, train_loss=0.6842, val_acc=55.16%, val_loss=0.6840]

seed 6:  20%|█▊       | 10/50 [36:21<2:03:17, 184.94s/it, best=55.16%, train_loss=0.6842, val_acc=55.13%, val_loss=0.6840]

seed 6:  22%|█▉       | 11/50 [36:21<1:56:58, 179.97s/it, best=55.16%, train_loss=0.6842, val_acc=55.13%, val_loss=0.6840]

seed 6:  22%|█▉       | 11/50 [39:12<1:56:58, 179.97s/it, best=55.16%, train_loss=0.6841, val_acc=55.10%, val_loss=0.6840]

seed 6:  24%|██▏      | 12/50 [39:12<1:52:18, 177.33s/it, best=55.16%, train_loss=0.6841, val_acc=55.10%, val_loss=0.6840]

seed 6:  24%|██▏      | 12/50 [42:03<1:52:18, 177.33s/it, best=55.16%, train_loss=0.6840, val_acc=55.10%, val_loss=0.6840]

seed 6:  26%|██▎      | 13/50 [42:03<1:48:09, 175.39s/it, best=55.16%, train_loss=0.6840, val_acc=55.10%, val_loss=0.6840]

seed 6:  26%|██▎      | 13/50 [44:54<1:48:09, 175.39s/it, best=55.16%, train_loss=0.6839, val_acc=55.04%, val_loss=0.6841]

seed 6:  28%|██▌      | 14/50 [44:54<1:44:26, 174.08s/it, best=55.16%, train_loss=0.6839, val_acc=55.04%, val_loss=0.6841]

seed 6:  28%|██▌      | 14/50 [47:44<1:44:26, 174.08s/it, best=55.16%, train_loss=0.6839, val_acc=55.12%, val_loss=0.6840]

seed 6:  30%|██▋      | 15/50 [47:44<1:40:55, 173.01s/it, best=55.16%, train_loss=0.6839, val_acc=55.12%, val_loss=0.6840]

seed 6:  30%|██▋      | 15/50 [50:36<1:40:55, 173.01s/it, best=55.16%, train_loss=0.6838, val_acc=55.05%, val_loss=0.6842]

seed 6:  32%|██▉      | 16/50 [50:36<1:37:44, 172.50s/it, best=55.16%, train_loss=0.6838, val_acc=55.05%, val_loss=0.6842]

seed 6:  32%|██▉      | 16/50 [53:27<1:37:44, 172.50s/it, best=55.16%, train_loss=0.6837, val_acc=55.14%, val_loss=0.6839]

seed 6:  34%|███      | 17/50 [53:27<1:34:41, 172.16s/it, best=55.16%, train_loss=0.6837, val_acc=55.14%, val_loss=0.6839]

seed 6:  34%|███      | 17/50 [56:17<1:34:41, 172.16s/it, best=55.16%, train_loss=0.6832, val_acc=55.16%, val_loss=0.6838]

seed 6:  36%|███▏     | 18/50 [56:17<1:31:28, 171.51s/it, best=55.16%, train_loss=0.6832, val_acc=55.16%, val_loss=0.6838]

seed 6:  36%|███▏     | 18/50 [59:06<1:31:28, 171.51s/it, best=55.16%, train_loss=0.6831, val_acc=55.15%, val_loss=0.6838]

seed 6:  38%|███▍     | 19/50 [59:06<1:28:15, 170.81s/it, best=55.16%, train_loss=0.6831, val_acc=55.15%, val_loss=0.6838]

seed 6:  38%|██▋    | 19/50 [1:01:55<1:28:15, 170.81s/it, best=55.17%, train_loss=0.6830, val_acc=55.17%, val_loss=0.6837]

seed 6:  40%|██▊    | 20/50 [1:01:55<1:25:00, 170.02s/it, best=55.17%, train_loss=0.6830, val_acc=55.17%, val_loss=0.6837]

seed 6:  40%|██▊    | 20/50 [1:04:43<1:25:00, 170.02s/it, best=55.17%, train_loss=0.6829, val_acc=55.16%, val_loss=0.6838]

seed 6:  42%|██▉    | 21/50 [1:04:43<1:21:57, 169.57s/it, best=55.17%, train_loss=0.6829, val_acc=55.16%, val_loss=0.6838]

seed 6:  42%|██▉    | 21/50 [1:07:31<1:21:57, 169.57s/it, best=55.18%, train_loss=0.6829, val_acc=55.18%, val_loss=0.6838]

seed 6:  44%|███    | 22/50 [1:07:31<1:18:55, 169.13s/it, best=55.18%, train_loss=0.6829, val_acc=55.18%, val_loss=0.6838]

seed 6:  44%|███    | 22/50 [1:10:21<1:18:55, 169.13s/it, best=55.18%, train_loss=0.6829, val_acc=55.18%, val_loss=0.6838]

seed 6:  46%|███▏   | 23/50 [1:10:21<1:16:13, 169.37s/it, best=55.18%, train_loss=0.6829, val_acc=55.18%, val_loss=0.6838]

seed 6:  46%|███▏   | 23/50 [1:13:11<1:16:13, 169.37s/it, best=55.18%, train_loss=0.6829, val_acc=55.16%, val_loss=0.6838]

seed 6:  48%|███▎   | 24/50 [1:13:11<1:13:26, 169.49s/it, best=55.18%, train_loss=0.6829, val_acc=55.16%, val_loss=0.6838]

seed 6:  48%|███▎   | 24/50 [1:16:00<1:13:26, 169.49s/it, best=55.19%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6838]

seed 6:  48%|▍| 24/50 [1:16:00<1:13:26, 169.49s/it, early_stop=epoch 25, train_loss=0.6828, val_acc=55.19%, val_loss=0.683

ensemble runs:  70%|███████████████████████████████████████▏                | 7/10 [10:32:29<4:02:13, 4844.40s/it, seed=6]

ensemble runs:  70%|███████████████████████████████████████▏                | 7/10 [10:32:29<4:02:13, 4844.40s/it, seed=7]

seed 7:   0%|                                                                                      | 0/50 [00:00<?, ?it/s]

seed 7:   0%|                     | 0/50 [02:49<?, ?it/s, best=54.40%, train_loss=0.6991, val_acc=54.40%, val_loss=0.6872]

seed 7:   2%|▏         | 1/50 [02:49<2:18:44, 169.89s/it, best=54.40%, train_loss=0.6991, val_acc=54.40%, val_loss=0.6872]

seed 7:   2%|▏         | 1/50 [05:42<2:18:44, 169.89s/it, best=54.40%, train_loss=0.6903, val_acc=53.85%, val_loss=0.6890]

seed 7:   4%|▍         | 2/50 [05:42<2:17:00, 171.26s/it, best=54.40%, train_loss=0.6903, val_acc=53.85%, val_loss=0.6890]

seed 7:   4%|▍         | 2/50 [08:34<2:17:00, 171.26s/it, best=54.89%, train_loss=0.6871, val_acc=54.89%, val_loss=0.6851]

seed 7:   6%|▌         | 3/50 [08:34<2:14:32, 171.76s/it, best=54.89%, train_loss=0.6871, val_acc=54.89%, val_loss=0.6851]

seed 7:   6%|▌         | 3/50 [11:25<2:14:32, 171.76s/it, best=54.97%, train_loss=0.6856, val_acc=54.97%, val_loss=0.6848]

seed 7:   8%|▊         | 4/50 [11:25<2:11:31, 171.55s/it, best=54.97%, train_loss=0.6856, val_acc=54.97%, val_loss=0.6848]

seed 7:   8%|▊         | 4/50 [14:16<2:11:31, 171.55s/it, best=55.03%, train_loss=0.6850, val_acc=55.03%, val_loss=0.6843]

seed 7:  10%|█         | 5/50 [14:16<2:08:34, 171.44s/it, best=55.03%, train_loss=0.6850, val_acc=55.03%, val_loss=0.6843]

seed 7:  10%|█         | 5/50 [17:08<2:08:34, 171.44s/it, best=55.09%, train_loss=0.6847, val_acc=55.09%, val_loss=0.6843]

seed 7:  12%|█▏        | 6/50 [17:08<2:05:37, 171.32s/it, best=55.09%, train_loss=0.6847, val_acc=55.09%, val_loss=0.6843]

seed 7:  12%|█▏        | 6/50 [19:57<2:05:37, 171.32s/it, best=55.09%, train_loss=0.6845, val_acc=55.09%, val_loss=0.6841]

seed 7:  14%|█▍        | 7/50 [19:57<2:02:22, 170.76s/it, best=55.09%, train_loss=0.6845, val_acc=55.09%, val_loss=0.6841]

seed 7:  14%|█▍        | 7/50 [22:46<2:02:22, 170.76s/it, best=55.11%, train_loss=0.6844, val_acc=55.11%, val_loss=0.6842]

seed 7:  16%|█▌        | 8/50 [22:46<1:59:00, 170.02s/it, best=55.11%, train_loss=0.6844, val_acc=55.11%, val_loss=0.6842]

seed 7:  16%|█▌        | 8/50 [25:34<1:59:00, 170.02s/it, best=55.13%, train_loss=0.6843, val_acc=55.13%, val_loss=0.6840]

seed 7:  18%|█▊        | 9/50 [25:34<1:55:52, 169.57s/it, best=55.13%, train_loss=0.6843, val_acc=55.13%, val_loss=0.6840]

seed 7:  18%|█▊        | 9/50 [28:25<1:55:52, 169.57s/it, best=55.13%, train_loss=0.6842, val_acc=55.10%, val_loss=0.6841]

seed 7:  20%|█▊       | 10/50 [28:25<1:53:21, 170.03s/it, best=55.13%, train_loss=0.6842, val_acc=55.10%, val_loss=0.6841]

seed 7:  20%|█▊       | 10/50 [31:16<1:53:21, 170.03s/it, best=55.13%, train_loss=0.6841, val_acc=55.13%, val_loss=0.6842]

seed 7:  22%|█▉       | 11/50 [31:16<1:50:45, 170.40s/it, best=55.13%, train_loss=0.6841, val_acc=55.13%, val_loss=0.6842]

seed 7:  22%|█▉       | 11/50 [34:09<1:50:45, 170.40s/it, best=55.13%, train_loss=0.6840, val_acc=55.10%, val_loss=0.6841]

seed 7:  24%|██▏      | 12/50 [34:09<1:48:16, 170.97s/it, best=55.13%, train_loss=0.6840, val_acc=55.10%, val_loss=0.6841]

seed 7:  24%|██▏      | 12/50 [36:58<1:48:16, 170.97s/it, best=55.14%, train_loss=0.6840, val_acc=55.14%, val_loss=0.6840]

seed 7:  26%|██▎      | 13/50 [36:58<1:45:08, 170.49s/it, best=55.14%, train_loss=0.6840, val_acc=55.14%, val_loss=0.6840]

seed 7:  26%|██▎      | 13/50 [39:47<1:45:08, 170.49s/it, best=55.14%, train_loss=0.6839, val_acc=55.07%, val_loss=0.6841]

seed 7:  28%|██▌      | 14/50 [39:47<1:41:56, 169.91s/it, best=55.14%, train_loss=0.6839, val_acc=55.07%, val_loss=0.6841]

seed 7:  28%|██▌      | 14/50 [42:36<1:41:56, 169.91s/it, best=55.14%, train_loss=0.6838, val_acc=55.10%, val_loss=0.6841]

seed 7:  30%|██▋      | 15/50 [42:36<1:38:57, 169.66s/it, best=55.14%, train_loss=0.6838, val_acc=55.10%, val_loss=0.6841]

seed 7:  30%|██▋      | 15/50 [45:27<1:38:57, 169.66s/it, best=55.19%, train_loss=0.6833, val_acc=55.19%, val_loss=0.6839]

seed 7:  32%|██▉      | 16/50 [45:27<1:36:25, 170.15s/it, best=55.19%, train_loss=0.6833, val_acc=55.19%, val_loss=0.6839]

seed 7:  32%|██▉      | 16/50 [48:20<1:36:25, 170.15s/it, best=55.20%, train_loss=0.6832, val_acc=55.20%, val_loss=0.6838]

seed 7:  34%|███      | 17/50 [48:20<1:34:00, 170.93s/it, best=55.20%, train_loss=0.6832, val_acc=55.20%, val_loss=0.6838]

seed 7:  34%|███      | 17/50 [51:12<1:34:00, 170.93s/it, best=55.20%, train_loss=0.6831, val_acc=55.18%, val_loss=0.6839]

seed 7:  36%|███▏     | 18/50 [51:12<1:31:22, 171.33s/it, best=55.20%, train_loss=0.6831, val_acc=55.18%, val_loss=0.6839]

seed 7:  36%|███▏     | 18/50 [54:02<1:31:22, 171.33s/it, best=55.20%, train_loss=0.6831, val_acc=55.18%, val_loss=0.6838]

seed 7:  38%|███▍     | 19/50 [54:02<1:28:15, 170.82s/it, best=55.20%, train_loss=0.6831, val_acc=55.18%, val_loss=0.6838]

seed 7:  38%|███▍     | 19/50 [56:50<1:28:15, 170.82s/it, best=55.20%, train_loss=0.6830, val_acc=55.18%, val_loss=0.6838]

seed 7:  40%|███▌     | 20/50 [56:50<1:25:01, 170.05s/it, best=55.20%, train_loss=0.6830, val_acc=55.18%, val_loss=0.6838]

seed 7:  40%|███▌     | 20/50 [59:41<1:25:01, 170.05s/it, best=55.20%, train_loss=0.6829, val_acc=55.18%, val_loss=0.6838]

seed 7:  42%|███▊     | 21/50 [59:41<1:22:22, 170.43s/it, best=55.20%, train_loss=0.6829, val_acc=55.18%, val_loss=0.6838]

seed 7:  42%|██▉    | 21/50 [1:02:33<1:22:22, 170.43s/it, best=55.20%, train_loss=0.6829, val_acc=55.18%, val_loss=0.6838]

seed 7:  44%|███    | 22/50 [1:02:33<1:19:39, 170.71s/it, best=55.20%, train_loss=0.6829, val_acc=55.18%, val_loss=0.6838]

seed 7:  44%|███    | 22/50 [1:05:24<1:19:39, 170.71s/it, best=55.20%, train_loss=0.6829, val_acc=55.19%, val_loss=0.6838]

seed 7:  46%|███▏   | 23/50 [1:05:24<1:16:58, 171.06s/it, best=55.20%, train_loss=0.6829, val_acc=55.19%, val_loss=0.6838]

seed 7:  46%|███▏   | 23/50 [1:08:16<1:16:58, 171.06s/it, best=55.20%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6838]

seed 7:  48%|███▎   | 24/50 [1:08:16<1:14:12, 171.26s/it, best=55.20%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6838]

seed 7:  48%|███▎   | 24/50 [1:11:08<1:14:12, 171.26s/it, best=55.20%, train_loss=0.6829, val_acc=55.19%, val_loss=0.6838]

seed 7:  50%|███▌   | 25/50 [1:11:08<1:11:23, 171.36s/it, best=55.20%, train_loss=0.6829, val_acc=55.19%, val_loss=0.6838]

seed 7:  50%|███▌   | 25/50 [1:13:59<1:11:23, 171.36s/it, best=55.20%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6838]

seed 7:  52%|███▋   | 26/50 [1:13:59<1:08:34, 171.45s/it, best=55.20%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6838]

seed 7:  52%|███▋   | 26/50 [1:16:51<1:08:34, 171.45s/it, best=55.20%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6838]

seed 7:  54%|███▊   | 27/50 [1:16:51<1:05:42, 171.40s/it, best=55.20%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6838]

seed 7:  54%|███▊   | 27/50 [1:19:42<1:05:42, 171.40s/it, best=55.20%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6838]

seed 7:  56%|███▉   | 28/50 [1:19:42<1:02:49, 171.35s/it, best=55.20%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6838]

seed 7:  56%|███▉   | 28/50 [1:22:35<1:02:49, 171.35s/it, best=55.20%, train_loss=0.6828, val_acc=55.19%, val_loss=0.6838]

seed 7:  56%|▌| 28/50 [1:22:35<1:02:49, 171.35s/it, early_stop=epoch 29, train_loss=0.6828, val_acc=55.19%, val_loss=0.683

ensemble runs:  80%|████████████████████████████████████████████▊           | 8/10 [11:55:10<2:42:43, 4881.56s/it, seed=7]

ensemble runs:  80%|████████████████████████████████████████████▊           | 8/10 [11:55:10<2:42:43, 4881.56s/it, seed=8]

seed 8:   0%|                                                                                      | 0/50 [00:00<?, ?it/s]

seed 8:   0%|                     | 0/50 [02:52<?, ?it/s, best=54.34%, train_loss=0.6988, val_acc=54.34%, val_loss=0.6862]

seed 8:   2%|▏         | 1/50 [02:52<2:20:40, 172.25s/it, best=54.34%, train_loss=0.6988, val_acc=54.34%, val_loss=0.6862]

seed 8:   2%|▏         | 1/50 [05:44<2:20:40, 172.25s/it, best=54.85%, train_loss=0.6901, val_acc=54.85%, val_loss=0.6853]

seed 8:   4%|▍         | 2/50 [05:44<2:17:37, 172.03s/it, best=54.85%, train_loss=0.6901, val_acc=54.85%, val_loss=0.6853]

seed 8:   4%|▍         | 2/50 [08:35<2:17:37, 172.03s/it, best=54.85%, train_loss=0.6870, val_acc=54.85%, val_loss=0.6850]

seed 8:   6%|▌         | 3/50 [08:35<2:14:40, 171.92s/it, best=54.85%, train_loss=0.6870, val_acc=54.85%, val_loss=0.6850]

seed 8:   6%|▌         | 3/50 [11:27<2:14:40, 171.92s/it, best=54.96%, train_loss=0.6855, val_acc=54.96%, val_loss=0.6848]

seed 8:   8%|▊         | 4/50 [11:27<2:11:49, 171.95s/it, best=54.96%, train_loss=0.6855, val_acc=54.96%, val_loss=0.6848]

seed 8:   8%|▊         | 4/50 [14:19<2:11:49, 171.95s/it, best=55.09%, train_loss=0.6850, val_acc=55.09%, val_loss=0.6842]

seed 8:  10%|█         | 5/50 [14:19<2:08:45, 171.67s/it, best=55.09%, train_loss=0.6850, val_acc=55.09%, val_loss=0.6842]

seed 8:  10%|█         | 5/50 [17:10<2:08:45, 171.67s/it, best=55.09%, train_loss=0.6847, val_acc=55.08%, val_loss=0.6843]

seed 8:  12%|█▏        | 6/50 [17:10<2:05:55, 171.71s/it, best=55.09%, train_loss=0.6847, val_acc=55.08%, val_loss=0.6843]

seed 8:  12%|█▏        | 6/50 [20:02<2:05:55, 171.71s/it, best=55.09%, train_loss=0.6846, val_acc=55.08%, val_loss=0.6843]

seed 8:  14%|█▍        | 7/50 [20:02<2:02:58, 171.60s/it, best=55.09%, train_loss=0.6846, val_acc=55.08%, val_loss=0.6843]

seed 8:  14%|█▍        | 7/50 [22:53<2:02:58, 171.60s/it, best=55.09%, train_loss=0.6844, val_acc=55.06%, val_loss=0.6842]

seed 8:  16%|█▌        | 8/50 [22:53<2:00:01, 171.47s/it, best=55.09%, train_loss=0.6844, val_acc=55.06%, val_loss=0.6842]

seed 8:  16%|█▌        | 8/50 [25:46<2:00:01, 171.47s/it, best=55.17%, train_loss=0.6843, val_acc=55.17%, val_loss=0.6841]

seed 8:  18%|█▊        | 9/50 [25:46<1:57:35, 172.09s/it, best=55.17%, train_loss=0.6843, val_acc=55.17%, val_loss=0.6841]

seed 8:  18%|█▊        | 9/50 [28:29<1:57:35, 172.09s/it, best=55.17%, train_loss=0.6843, val_acc=55.17%, val_loss=0.6840]

seed 8:  20%|█▊       | 10/50 [28:29<1:52:48, 169.21s/it, best=55.17%, train_loss=0.6843, val_acc=55.17%, val_loss=0.6840]

seed 8:  20%|█▊       | 10/50 [30:17<1:52:48, 169.21s/it, best=55.17%, train_loss=0.6842, val_acc=55.14%, val_loss=0.6841]

seed 8:  22%|█▉       | 11/50 [30:17<1:37:41, 150.30s/it, best=55.17%, train_loss=0.6842, val_acc=55.14%, val_loss=0.6841]

seed 8:  22%|█▉       | 11/50 [32:04<1:37:41, 150.30s/it, best=55.17%, train_loss=0.6841, val_acc=55.10%, val_loss=0.6841]

seed 8:  24%|██▏      | 12/50 [32:04<1:26:54, 137.23s/it, best=55.17%, train_loss=0.6841, val_acc=55.10%, val_loss=0.6841]

seed 8:  24%|██▏      | 12/50 [33:51<1:26:54, 137.23s/it, best=55.17%, train_loss=0.6840, val_acc=55.17%, val_loss=0.6840]

seed 8:  26%|██▎      | 13/50 [33:51<1:19:00, 128.11s/it, best=55.17%, train_loss=0.6840, val_acc=55.17%, val_loss=0.6840]

seed 8:  26%|██▎      | 13/50 [35:38<1:19:00, 128.11s/it, best=55.17%, train_loss=0.6839, val_acc=55.13%, val_loss=0.6840]

seed 8:  28%|██▌      | 14/50 [35:38<1:13:04, 121.79s/it, best=55.17%, train_loss=0.6839, val_acc=55.13%, val_loss=0.6840]

seed 8:  28%|██▌      | 14/50 [37:25<1:13:04, 121.79s/it, best=55.17%, train_loss=0.6839, val_acc=55.10%, val_loss=0.6841]

seed 8:  30%|██▋      | 15/50 [37:25<1:08:23, 117.23s/it, best=55.17%, train_loss=0.6839, val_acc=55.10%, val_loss=0.6841]

seed 8:  30%|██▋      | 15/50 [39:12<1:08:23, 117.23s/it, best=55.17%, train_loss=0.6838, val_acc=55.16%, val_loss=0.6839]

seed 8:  32%|██▉      | 16/50 [39:12<1:04:41, 114.17s/it, best=55.17%, train_loss=0.6838, val_acc=55.16%, val_loss=0.6839]

seed 8:  32%|██▉      | 16/50 [40:59<1:04:41, 114.17s/it, best=55.17%, train_loss=0.6837, val_acc=55.11%, val_loss=0.6840]

seed 8:  34%|███      | 17/50 [40:59<1:01:33, 111.94s/it, best=55.17%, train_loss=0.6837, val_acc=55.11%, val_loss=0.6840]

seed 8:  34%|███      | 17/50 [42:46<1:01:33, 111.94s/it, best=55.18%, train_loss=0.6837, val_acc=55.18%, val_loss=0.6840]

seed 8:  36%|███▉       | 18/50 [42:46<58:55, 110.49s/it, best=55.18%, train_loss=0.6837, val_acc=55.18%, val_loss=0.6840]

seed 8:  36%|███▉       | 18/50 [44:33<58:55, 110.49s/it, best=55.18%, train_loss=0.6836, val_acc=55.08%, val_loss=0.6841]

seed 8:  38%|████▏      | 19/50 [44:33<56:37, 109.59s/it, best=55.18%, train_loss=0.6836, val_acc=55.08%, val_loss=0.6841]

seed 8:  38%|████▏      | 19/50 [46:21<56:37, 109.59s/it, best=55.18%, train_loss=0.6835, val_acc=55.12%, val_loss=0.6840]

seed 8:  40%|████▍      | 20/50 [46:21<54:27, 108.90s/it, best=55.18%, train_loss=0.6835, val_acc=55.12%, val_loss=0.6840]

seed 8:  40%|████▍      | 20/50 [48:08<54:27, 108.90s/it, best=55.18%, train_loss=0.6834, val_acc=55.00%, val_loss=0.6842]

seed 8:  40%|█▏ | 20/50 [48:08<54:27, 108.90s/it, early_stop=epoch 21, train_loss=0.6834, val_acc=55.00%, val_loss=0.6842]

ensemble runs:  90%|██████████████████████████████████████████████████▍     | 9/10 [12:43:24<1:11:00, 4260.20s/it, seed=8]

ensemble runs:  90%|██████████████████████████████████████████████████▍     | 9/10 [12:43:24<1:11:00, 4260.20s/it, seed=9]

seed 9:   0%|                                                                                      | 0/50 [00:00<?, ?it/s]

seed 9:   0%|                     | 0/50 [01:46<?, ?it/s, best=54.18%, train_loss=0.6985, val_acc=54.18%, val_loss=0.6870]

seed 9:   2%|▏         | 1/50 [01:46<1:26:57, 106.48s/it, best=54.18%, train_loss=0.6985, val_acc=54.18%, val_loss=0.6870]

seed 9:   2%|▏         | 1/50 [03:34<1:26:57, 106.48s/it, best=54.20%, train_loss=0.6900, val_acc=54.20%, val_loss=0.6863]

seed 9:   4%|▍         | 2/50 [03:34<1:25:41, 107.12s/it, best=54.20%, train_loss=0.6900, val_acc=54.20%, val_loss=0.6863]

seed 9:   4%|▍         | 2/50 [05:21<1:25:41, 107.12s/it, best=54.77%, train_loss=0.6869, val_acc=54.77%, val_loss=0.6852]

seed 9:   6%|▌         | 3/50 [05:21<1:24:01, 107.26s/it, best=54.77%, train_loss=0.6869, val_acc=54.77%, val_loss=0.6852]

seed 9:   6%|▌         | 3/50 [07:09<1:24:01, 107.26s/it, best=54.81%, train_loss=0.6854, val_acc=54.81%, val_loss=0.6850]

seed 9:   8%|▊         | 4/50 [07:09<1:22:20, 107.39s/it, best=54.81%, train_loss=0.6854, val_acc=54.81%, val_loss=0.6850]

seed 9:   8%|▊         | 4/50 [08:55<1:22:20, 107.39s/it, best=55.05%, train_loss=0.6849, val_acc=55.05%, val_loss=0.6844]

seed 9:  10%|█         | 5/50 [08:55<1:20:20, 107.11s/it, best=55.05%, train_loss=0.6849, val_acc=55.05%, val_loss=0.6844]

seed 9:  10%|█         | 5/50 [10:43<1:20:20, 107.11s/it, best=55.05%, train_loss=0.6846, val_acc=55.02%, val_loss=0.6844]

seed 9:  12%|█▏        | 6/50 [10:43<1:18:39, 107.25s/it, best=55.05%, train_loss=0.6846, val_acc=55.02%, val_loss=0.6844]

seed 9:  12%|█▏        | 6/50 [12:29<1:18:39, 107.25s/it, best=55.05%, train_loss=0.6844, val_acc=55.04%, val_loss=0.6844]

seed 9:  14%|█▍        | 7/50 [12:29<1:16:42, 107.04s/it, best=55.05%, train_loss=0.6844, val_acc=55.04%, val_loss=0.6844]

seed 9:  14%|█▍        | 7/50 [14:16<1:16:42, 107.04s/it, best=55.06%, train_loss=0.6843, val_acc=55.06%, val_loss=0.6843]

seed 9:  16%|█▌        | 8/50 [14:16<1:14:53, 106.99s/it, best=55.06%, train_loss=0.6843, val_acc=55.06%, val_loss=0.6843]

seed 9:  16%|█▌        | 8/50 [16:04<1:14:53, 106.99s/it, best=55.11%, train_loss=0.6842, val_acc=55.11%, val_loss=0.6841]

seed 9:  18%|█▊        | 9/50 [16:04<1:13:11, 107.11s/it, best=55.11%, train_loss=0.6842, val_acc=55.11%, val_loss=0.6841]

seed 9:  18%|█▊        | 9/50 [17:51<1:13:11, 107.11s/it, best=55.11%, train_loss=0.6841, val_acc=55.04%, val_loss=0.6844]

seed 9:  20%|█▊       | 10/50 [17:51<1:11:24, 107.11s/it, best=55.11%, train_loss=0.6841, val_acc=55.04%, val_loss=0.6844]

seed 9:  20%|█▊       | 10/50 [19:38<1:11:24, 107.11s/it, best=55.13%, train_loss=0.6840, val_acc=55.13%, val_loss=0.6842]

seed 9:  22%|█▉       | 11/50 [19:38<1:09:40, 107.20s/it, best=55.13%, train_loss=0.6840, val_acc=55.13%, val_loss=0.6842]

seed 9:  22%|█▉       | 11/50 [21:25<1:09:40, 107.20s/it, best=55.13%, train_loss=0.6840, val_acc=55.08%, val_loss=0.6843]

seed 9:  24%|██▏      | 12/50 [21:25<1:07:53, 107.21s/it, best=55.13%, train_loss=0.6840, val_acc=55.08%, val_loss=0.6843]

seed 9:  24%|██▏      | 12/50 [23:12<1:07:53, 107.21s/it, best=55.13%, train_loss=0.6839, val_acc=55.02%, val_loss=0.6843]

seed 9:  26%|██▎      | 13/50 [23:12<1:05:59, 107.01s/it, best=55.13%, train_loss=0.6839, val_acc=55.02%, val_loss=0.6843]

seed 9:  26%|██▎      | 13/50 [24:59<1:05:59, 107.01s/it, best=55.13%, train_loss=0.6838, val_acc=55.08%, val_loss=0.6842]

seed 9:  26%|▎| 13/50 [24:59<1:05:59, 107.01s/it, early_stop=epoch 14, train_loss=0.6838, val_acc=55.08%, val_loss=0.6842]

ensemble runs: 100%|█████████████████████████████████████████████████████████| 10/10 [13:08:27<00:00, 3408.79s/it, seed=9]

ensemble runs: 100%|█████████████████████████████████████████████████████████| 10/10 [13:08:27<00:00, 4730.70s/it, seed=9]

In [6]:
# import torch
# import pandas as pd
# import matplotlib.pyplot as plt


# result = pd.read_csv("/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_training_history_I5R5_seed0.csv")

# plt.figure(figsize=(8, 5))
# plt.plot(result["epoch"], result["val_loss"], label="val_loss", marker="o")
# plt.xlabel("Epoch")
# plt.xticks(result["epoch"])
# plt.ylabel("Loss")
# plt.title("Training / Validation Loss")
# plt.legend()
# plt.grid(True, alpha=0.3)
# plt.show()

In [7]:
# plt.figure(figsize=(8, 5))
# plt.plot(result["epoch"], result["val_acc"], label="val_acc", marker="o")
# plt.xlabel("Epoch")
# plt.ylabel("Accuracy")
# plt.title("Validation Accuracy")
# plt.legend()
# plt.grid(True, alpha=0.3)
# plt.show()

# Test

In [8]:
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error, accuracy_score, log_loss
import model
import importlib
importlib.reload(model)

root = Path("/home/iof_314707035/Jasper")

# 1. 讀取 test data
market = "US_1993_2020"
dataset_dir = root / "Reimage_price_trends" / "data" / "training_data" / market / "I5R5S5_week"

X_test = np.load(dataset_dir / "X_test.npy")
y_test = np.load(dataset_dir / "y_test.npy")

print(X_test.shape, y_test.shape)

(5899098, 32, 15) (5899098,)

In [9]:
model_dir = root / "Reimage_price_trends" / "models" / "US_1993_2020" / "I5R5"
RUN_SEEDS = list(range(10))
seeds = list(RUN_SEEDS)

summary_frames = []
checkpoint_paths = []
for seed in seeds:
    summary_path = model_dir / f"US_1993_2020_training_summary_I5R5_seed{seed}.csv"
    summary_df = pd.read_csv(summary_path)
    best_path = Path(summary_df.loc[0, "best_path"])
    if not best_path.is_absolute():
        best_path = root / "Reimage_price_trends" / best_path
    checkpoint_paths.append(str(best_path))
    summary_frames.append(summary_df.assign(seed=seed, resolved_best_path=str(best_path)))

ensemble_summary_df = pd.concat(summary_frames, ignore_index=True)
print("ensemble checkpoints:")
for path in checkpoint_paths:
    print(path)

ensemble checkpoints:
/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_best_model_I5R5_seed0.pth
/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_best_model_I5R5_seed1.pth
/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_best_model_I5R5_seed2.pth
/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_best_model_I5R5_seed3.pth
/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_best_model_I5R5_seed4.pth
/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_best_model_I5R5_seed5.pth
/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_best_model_I5R5_seed6.pth
/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_best_model_I5R5_seed7.pth
/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_best_model_I5R5_seed8.pth
/home/iof_314707035/Jasper/Reimage_price_trends/models/US_1993_2020/I5R5/US_1993_2020_best_model_I5R5_seed9.pth

In [10]:
pred_prob = model.average_ensemble_predictions(
    X_test,
    checkpoint_paths,
    batch_size=256,
    device="cuda"
)

pred_prob = np.asarray(pred_prob).reshape(-1)
pred_label = (pred_prob > 0.5).astype(int)

In [11]:
test_mse = mean_squared_error(y_test, pred_prob)
test_acc = accuracy_score(y_test, pred_label)
test_logloss = log_loss(y_test, pred_prob)

print("ensemble checkpoints:", len(checkpoint_paths))
print("test MSE:", test_mse)
print("test accuracy:", test_acc)
print("test logloss:", test_logloss)

ensemble checkpoints: 10
test MSE: 0.25005435943603516
test accuracy: 0.5130928491101521
test logloss: 0.6932681953711476

In [12]:
import pandas as pd
import portfolio_backtest as pb

pred_df = pb.make_prediction_frame(
    meta=meta_test,
    y_true=y_test,
    pred_prob=pred_prob,
    pred_label_threshold=0.5,
)


seed_tag = "seed" + "_".join(str(seed) for seed in seeds)
run_dir = model_dir / f"ensemble_{seed_tag}"
grouped_df, portfolio_returns, summary = pb.run_decile_backtest(
    pred_df,
    n_groups=10,
    R=5,
    output_dir=str(run_dir / "backtest_ensemble_mean_prob"),
    prefix="i5r5_ensemble_mean_prob",
)

summary

,strategy,n_periods,periods_per_year,annualization_method,mean_period_return,period_volatility,annualized_return,annualized_volatility,sharpe,compound_annualized_return,compound_sharpe,cumulative_return,max_drawdown,positive_period_rate
0,long_top_ret,991,52.0,js_cnn,0.009621,0.030236,0.500311,0.218038,2.294607,0.645295,2.294607,8.470322e+03,-0.352859,0.676085
1,short_bottom_ret,991,52.0,js_cnn,0.005098,0.021067,0.265111,0.151913,1.745153,0.302698,1.745153,1.237296e+02,-0.380855,0.580222
2,long_short_ret,991,52.0,js_cnn,0.014720,0.017904,0.765423,0.129109,5.928493,1.137943,5.928493,1.674768e+06,-0.045828,0.877901